apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: default
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/infrastructure/registry",
        "gc": true,
        "gcDelay": "1h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "realm": "zot",
        "auth": {
          "htpasswd": {
            "path": "/etc/zot/htpasswd"
          }
        },
        "accessControl": {
          "repositories": {
            "**": {
              "policies": [
                {
                  "users": ["pushuser"],
                  "actions": ["read", "create", "update"]
                },
                {
                  "users": ["pulluser"],
                  "actions": ["read"]
                },
                {
                  "users": ["_admin"],
                  "actions": ["read", "create", "update", "delete"]
                }
              ],
              "anonymousPolicy": []
            }
          }
        }
      },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        }
      }
    }
