apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: registry
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:wRp1StdVeDqdwF8NdozlKmcEW5GikyAOqaUBQ0TrZorbOSkTuRuINdJisbLdgLPg32CU+vu6eqcM5EbhFaHPBO1B0KK1wj+m0vA/ucGW+NodLJM+pDGEw7JbFEU+KAYGVez9F/thg1D29AMjQarjZdsrHhIb8d98C4iNb3FdVhwmoP/s5TCCipwm+FmNRHB2j1j0nH1sRUeopqqY0mevr7f26YpJCQQmuhI3ntw2wQuzPMZ+4duo5mXxmbKZlJnMyQIL0o+7+8nJMrIU5sdC85O31KZ+F41n2V2zFlKAEiwT0OAv6+3t9K09DNZO8RK2Pvsn9dBPUB2DhyidwywuoUW8fNpxJ6KILGnT3jZo5QEuSbwOMw==,iv:U0+YRLVnsi/QMt05g7UMDE5F5NGTAuWtKhlg+SurMuY=,tag:zSpaRVPD4ZCUvZQg5S0iAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1FtQmVYTWZxdWJ5S3Jr
            ejliWHFHTjFEb0s2elRZYVNHVDhRSWo3b1cwCkVKMmQ5ZkR4eU1xVmtlbDhOYzRn
            T1N0bWs4elJUKzhQRVc3dnErM21YS2cKLS0tIGQrRXhyYWs3bzNzdGpVdVkrODMv
            RUt1N05TaFRVV3R2S09ObytIQU1mVXMK9TmxBl1421YCl+RnsePB/huSIpf0BpxS
            BDpne/SWsvuTDRCEhWmAsdiJHxcu5T3uDwx/zXahUAkmkVW1Egm2bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T10:10:13Z"
    mac: ENC[AES256_GCM,data:YaYjfXgsj9Bvs/l6SjTUbfAsy6ChT6WZaW0Ti/5qwM+vd486ruVseNyJOqtj6maWl4IE12QXCzGUvaGk6tDKgVoe4AkTpzydbfHiwXg4+TPrxlCQLYJo+mbcrKe/Vrhz95wohW8aoPTyqaGudlR3tRSwlobpxYJ773QbDotPz0I=,iv:Uxu5dNAV2q2yhjVoWYqnnJOUvnxCZx+LUKkSdTEv/Aw=,tag:OFilTGZ+lz6muhEp7X22sQ==,type:str]
    version: 3.13.1
