apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: registry
type: Opaque
stringData:
    htpasswd: |
        pushuser:$2y$05$TZgsYcmuIWN0VWSqrkGFVu6GVTtv201BS539GB4AKmS5lOuPLJJ5a
        pulluser:$2y$05$NQjCGZhsSwfBujCpc9F/FOhvptvnjHDbSRuB2DlPACAZDb8K4UL/q
        _admin:$2y$05$rf8J6CELactVvrH5AFZL8e4AqNMF1z4qLNuF9xTch1JPQPvqJVqUy
        cipush:$2y$10$.QXlFHbhDnSu/H7hAargveSjD3ZWb1OVcqp1T7TcA2sRRqohl05nO
