apiVersion: v1
kind: Secret
metadata:
    name: zot-auth
    namespace: default
type: Opaque
stringData:
    pulluser-password: ENC[AES256_GCM,data:ZgoJJxLzO7EaUUBg,iv:nDmiJWCQOcHy98oZUmh1vVscIUKJsG04zjNY0I5T7Kw=,tag:4xDA9mh75+POrV6TWNbw8w==,type:str]
    pushuser-password: ENC[AES256_GCM,data:bnko/RthBIwdgb54,iv:4n+oyns1yrVBZyBhlAqc1PBVrqmjTHytz+fQ5H8Ue8s=,tag:1atZFZuHP+woni0a8qJArw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaVN1UTNjeVREYkt2VlRJ
            Zlp6U3BZSVk5TUJRSHN2ajNVb2VSRmhYZUdZClI4SFNFS2dIejJ6TW5uZFdZcHJO
            b0ZOcVNrSUFUbG1LMVlmN2lYazhOWUUKLS0tIDYxb0tBRk5XQ2M3K1UraGo1QkIr
            SUR4VFYvQTBmM1pTWEZWUzk5RTUyWmsKGFLBKbT7SN7U+zMSqMl9TU8SczaC84ce
            vgAqK5v2aTiTtnLSuTGMp1FWATCVmze+2EUwOp4x7sKgYZAouJ8O+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:10:36Z"
    mac: ENC[AES256_GCM,data:0BXMWSoUZnLzHRtREIdeWfgnsLRNxnudgR+17vVwrh45Dq2oeN3+JKjnjldgUfEQkoKW85fOkkNhYmSNxJdId2Xzo9erWZcFXPCb3MvyZU3I6+HyAwnui0pr09dPS29LC22H443nv6zazyllrMY4uHs175veZwZ7/uwKB6oURf0=,iv:CIEmm+RpEy13merzj5Rn+I/bKISgGtIA4lYJH1H/T0M=,tag:6PQYChQFPoTIAYXYYKuFeQ==,type:str]
    version: 3.13.1
