apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-chatbot
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-security-headers@kubernetescrd
    traefik.ingress.kubernetes.io/router.transport.responsetransport.flushinterval: "1"
spec:
  rules:
    - host: chatbot.aashutoshparajuli.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-chatbot
                port:
                  number: 80
