apiVersion: v1
kind: Secret
metadata:
    name: chatbot-secret
    namespace: default
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:3Vjdkg==,iv:SK3n4TrHBsnOLd3Wh6UwX6XTc4Knmdp5nAilJp+m83s=,tag:0li4hXAe2ILNVc736gnp2g==,type:str]
    DB_HOST: ENC[AES256_GCM,data:V7PfgjbBWdKyYHuzIu0/m2epI0SPmckuUhwacbDbiMrGSQ==,iv:cdlQkragakzySw4x6eK8FUWIQU//uHJC9bo7DSrkme4=,tag:uqq/Z8n/pYAfjjlEkxtIgw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:tu/WBw==,iv:kaE0nmOMbvkh9ZKvr0I57aaNVHOKhKOmIkE8llfqlpo=,tag:ML7J8fRNH3J007h1HZIebA==,type:str]
    DB_USER: ENC[AES256_GCM,data:TSBBrOLJkA==,iv:esMXAUdnt8odzax8bTxFwA/QyDBKu1xuUPUb2sia6LY=,tag:9BkJqkAFGoV+VixmfNJXmQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:thRjD2AJmN0=,iv:5keN7izX9G1r3mlYv7Rp5TjG0qt9yCMnR/N4zj2NxA8=,tag:blD1FfQiSKmriwzsCPY7sw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:pk0sknINbW/gZwv0J5ft2g==,iv:NZzqcu35Blf/qVYVgYZVOvnG08xRsQRVIyvVg2Cyh/I=,tag:4TY4V39Ptg3EZyZ0lMko3g==,type:str]
    #ENC[AES256_GCM,data:UUhAfHl5k6M9Ea8ipWvvKjX+ZoY0yNWDTa/WDxrGCRu8IRsk/6NKk8EBfDT25G9KcA==,iv:ztFIVTsOrGsxuaq6U857jZUNtmuj91DgH4IBiGWUoe4=,tag:bfyqPPEL8/L7/pzwFWd+0Q==,type:comment]
    #ENC[AES256_GCM,data:rBYVwvurn6nKAkpJk80cLTetDS740ppSS1zN2rtT+wfDZodbAizhC6dbHiJoyk/3l7bD47+61KDlgc776nRb5lPVnXfe3jUUrG83gpYXTUUmeW2egg==,iv:BhYxAi7iul75Nmj0T1Ups+bGDYJ3TJn10ttwOfccPUw=,tag:YIdlwsC9GHsgrcKVIBjRlg==,type:comment]
    LLM_PROVIDER: ENC[AES256_GCM,data:Pwz9LfHVcjNp1g==,iv:mlvHVD/UICNc47zrbXRm631Ff6j2KgZR0f+opj9NoYQ=,tag:0x+ekVpji4qSFlPLQJ2M5g==,type:str]
    #ENC[AES256_GCM,data:WKzAix5OPCZTqPFsZV1p1Nvzpx7Ng5ugRy0pJcar,iv:eVGATUtjgvhHyDeiEFtfya7B2+dTabbiwMRdMEtg5bI=,tag:VvcqgDEDcMuNG2cV0nljnw==,type:comment]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:FiJlJ4gZgOFNwLdPoVfISG1VnN483l9nGBjprdLztYTi0Ruq+Gf7qtE86y99rOH9YTam6r4pcYQ1jMXGga1FbBbrAUkEqiBZyg==,iv:qdQVAWmK/GCesyk+g5/IR5WHseYMXvr2dlNgH91UJGg=,tag:tdckjqLKree/quIDQW54Dw==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:sN0sfuEH9PRmLDTY3X2keNgP9IOfePWOsiUnMi/Cl7O3,iv:xcEi0lBTxj6UJA+fOQUoAeGPcLRqH8knMYljZTnyN4E=,tag:AffIG78ikuYy0R0ZVZ7Jow==,type:str]
    #ENC[AES256_GCM,data:ABHb6goPvA03nB+BBz64jvJfzxNry8Gm300KLAdXSRN1L5RUH5AAm/1x6RhHRW1vOw76Whu5lgWYoofx6XLv0ZCRnHYpppr0VBiK/W68HTu7ycRqFg91Mw==,iv:ljOouI0OUutQIP7qqWy6xuULhkZZ1qNkPnaghnO3ZRY=,tag:6jfcTko1Utq5mMorS9VtIw==,type:comment]
    GITHUB_MODELS_TOKEN: ""
    GITHUB_MODELS_MODEL: ENC[AES256_GCM,data:EEp5o9oJcp9BjwCim2f7ZGLnE02NZd0qqa4=,iv:o6QBKzqHkNvwUvVLZ2FCG2/LQgeG1I5czpj6gXjLPkM=,tag:H7BjuudTLKYL8UhqHddS5g==,type:str]
    #ENC[AES256_GCM,data:cHE8Se6JdXkBJfX+MqOfHV0loTtNn3qCPihK1jJgS9kMIhaCPtk157U=,iv:VYCdZTHHr/fNSMbDMvbg+31FtG/TQW+PzYo9lw/voak=,tag:cG/q6dSNZwZ0BsxAOI7NXQ==,type:comment]
    GEMINI_API_KEY: ENC[AES256_GCM,data:fJhiAadg01cpEPXiiLfABa2saXpso5DitmdKOzL07kIfyfZxZS1kZzZ1Kl5GUlbzdo/Arns=,iv:5zBL2ntqhI87zH3Mdx/BGEE4DCxNjWgyUfNl12dYsaA=,tag:gfZqqKdHevb/xxg+eLHtxA==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:z939DC+O6eu45P39CVVPoQ==,iv:BY2YxZLq0uZGKvZ2eLOd52YPt5/AzMlnFNlROW+ZnUY=,tag:2qoAlg2FgB0NoxglokII+Q==,type:str]
    GEMINI_EMBED_MODEL: ENC[AES256_GCM,data:EuDSGHWfuMW6BMlybmKPZK3W,iv:s24I13rzVkGsGZF/E7+NjxZRzhuYsv1LYxEUcGgOa70=,tag:HQ1FLefCIV7kfb2PRcrNXw==,type:str]
    #ENC[AES256_GCM,data:MX2YqUo0DnlZ3ucJQsaau2H5fPA2ZkNf2LnCQqw49csRvRBP6SNFOXQ1yTNL6+vuWm6XYtSPN19rzq2+Fuq0hIMIEwo=,iv:/gvZdSGx76Kun5PDI6w8pADpTJILcSjLIwe/yiVgIaU=,tag:JKLdGoKXhx/BRw44AuNyRQ==,type:comment]
    #ENC[AES256_GCM,data:M1y1P+s41+vhuLnWtMsPeXv51GOkDtPjWu9GSMYsfoMvjJVl5emDdA==,iv:jJsqBaQqk0SNhzpYkE9CRdldQBYogQLYkUZk+i5DIO8=,tag:Jgdsezq+TcnHc76Nphs+wg==,type:comment]
    #ENC[AES256_GCM,data:T/Xplo/REIa/BJUdwzttIUZA+ZZ9Sok=,iv:qTgKR5hPR92NQDS+S7kZ5zxZvOrlhIsNNdTAQ1K5A+4=,tag:Za+N0TlzO48iLQShkTUDrw==,type:comment]
    #ENC[AES256_GCM,data:IpvWuWu95RSvFgAQzfWiEmKYkXbJlkOIC7p/KlzJy+ozCR6i+g==,iv:vrawxCGbF9VDm48Ghm6ZR/4QtCMPYcHZwJZzMGfuR6M=,tag:kxb/r8rm8ueOkXqNxF8xOw==,type:comment]
    #ENC[AES256_GCM,data:5t3ZjHMFo52ErjGZFRJ9Jlz2YX1ixrD9OsaJc3jVkk/wTQEzcpNZDmlrN9infQ/cqg==,iv:W2x+6HukwOn4fbZYi4eSO2MGoPsO5tS6hmvNvzZH/ak=,tag:7mdqVWfNPs8vbCEmpF931w==,type:comment]
    API_KEY: ENC[AES256_GCM,data:xmF9DHB69T3j4xM9,iv:tdx1CyDtzdJ823ekA9IBugaaqvoGNu9cqdhlAC7Ra1c=,tag:HuOlOAtlA6prEYkLMIA80g==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:wAenNZkATNBNfFlrArhRV6iQNlFIVjVVH6kg/XYPoVM=,iv:ZNX86EMlmWT9oLV+AojCZ8CJAxEKAjvqy6+XJExFofE=,tag:aoJl5w4EuePl3t252R4bcg==,type:str]
    #ENC[AES256_GCM,data:0JcW9BYU1dw8c5Gi6S0h8FedKxPMVINMajqqNiqi2bhEHhjlyBc/ftoh45ObPEyDs9k1a+wahQ==,iv:HYKutt8J1Z/ACgLsS4lQw61gIgn79z2DfDHBnOVYQhQ=,tag:1LUsm0AzQVsnnLg5Hjjg6w==,type:comment]
    IPINFO_API_KEY: ENC[AES256_GCM,data:X4JWzlmyf/739XyzjYw=,iv:VA0IBJk/OFZMtoOYBOAoqfZTAgFp17Rsajb1QNNXNGo=,tag:aMg2b5zI7yp3mhRLnRt6Iw==,type:str]
    #ENC[AES256_GCM,data:N/otvwz5NfvQVs1+mGkC9O8=,iv:uBU4fBdxtfFQCh689xJyg2hXI30S8t7pWFrgCgjkjlA=,tag:fcyF5Qvzv9wfr2KRp1Hgmg==,type:comment]
    MAX_FILE_SIZE_MB: ENC[AES256_GCM,data:SpA=,iv:bIosemD6960iutl8Xywq66TCjfIT2tKYGRF3nZZdyCY=,tag:xGZ5D19kWv5AkfTbz4OmZw==,type:str]
    MAX_PAGES: ENC[AES256_GCM,data:0Wju,iv:MSX3ImYqW+nw5ZOUC8bdOCis79HdBGcWeYsfRtXQJ4w=,tag:DGu2E3YvkFfzbl2qBzItVw==,type:str]
    PDF_DIR: ENC[AES256_GCM,data:Xpvw2A==,iv:4qzx2mnFFt6qGDld4KBlsRarh+Sl7ozZHNoJ8lElcs0=,tag:J5QHTUEpZIJiVIhHoXZiOw==,type:str]
    EMBED_BATCH_SIZE: ENC[AES256_GCM,data:vlQ=,iv:tKMyhoNPfiOHJ6klODrh9QLxpJou7aMXbhnXKOJfFAo=,tag:88ea2NHn437b68fk3gPK7Q==,type:str]
    #ENC[AES256_GCM,data:n96dxaJ2Y/2oFWG9Y3vswfI=,iv:c+ujOogYULJovSa7fjt9ZnIfa2lLIsIYAqcpB4YPc+o=,tag:G8Qffy0c7ycIhe+LGJSLUg==,type:comment]
    CONTEXT_TOKEN_LIMIT: ENC[AES256_GCM,data:0vh6yA==,iv:tl7PJZQFTs+Kqv/rVNDHslsmw2JG69kxYkir7T4iOCo=,tag:63zvrrkiRjIbOmpn/7yskw==,type:str]
    #ENC[AES256_GCM,data:OtTHQMY=,iv:MDwY9CmiZrCL4sZqwGQ7kUD2p/XzY+naHYkANwM6Uo0=,tag:EcqNvXGIsnR2X1Ez2i3bOQ==,type:comment]
    CORS_ORIGINS: ENC[AES256_GCM,data:1k2U9SVcuM+AEUlEDJEZDxkFRVvcZKiLXjWqACQ8PEf9N3MydMiVR7qdKoH1Bhr9fbNRtM+Y59Z2emcDK6Vj08YPBOHWWDc3LIqEbXHRow8U95UAGkPfKK6e1OXUlAWAwu4efUypAppMgAV6jz5YvWC3TlWNRRY9cd8L7nk=,iv:gUFUJWZHq/VUCoDLKMgWiCD0/KwHseJ+jN6GSK2i94I=,tag:2nf2XwJUiHN46ODZcZ4yDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbWRUY1RzWW8rdFU2S0Zo
            dzB6TThKdm92ZWp1S05Bb2RrbVNVUnJwSFdzClk2MThQOXJIMEFoUm5sdFo4VHdo
            Z1JheG9PQWNady9VWStZdFJjUzM4REEKLS0tIG9xeHBEQkUrMmlHS0ZGOHJlNEN2
            L3pSbmhDUzg5dkdWNHpZeUNzbElaWHcKFjzrKGwAi4c8MLAO2s7YCNv4O6yevDdF
            AC//KfpM7ELpxto9J73Gr9dfXl4K8T7DxB9cUT4gvJ39zNNOS81q7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T08:16:48Z"
    mac: ENC[AES256_GCM,data:kcuYSL6piROM6x60Fs1yxPxiaWig40RkZ+FKp/avA4MvPMmRZc/DEdAQ1xPwCYU3kXXT17nAo/XHFVBa0bFq+gPCTp4hIDu731vjnPluqQqxwAnUylmrsG3oVaff4BmZOyVz0mHo0umSdBA3LlFLTbLg+17nzIflE4oVCUlZinI=,iv:yOT5C34GQJpXvyIcSHBXuzO7SUpz2ALRExx5u6V8Cfg=,tag:cjibQSnpaXUMXr5nYvAgwg==,type:str]
    version: 3.13.1
