apiVersion: v1
kind: Secret
metadata:
    name: chatbot-secret
    namespace: default
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:678TMg==,iv:Z93kou5kYFK7lveBss00B34ZvZf5Oa/IvVRkXrET+Ss=,tag:YQdlCJJ41LTZ4w8lyYNTgg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:qMMgOQYeDhd/UBV6GVVpgz2iKZl7M0U62TLkA3DUeSjCAA==,iv:3Wv3xalx0Pz4D9z4HYGsnHk3PNO97E712iy29ZqW1jc=,tag:dJ3DWRh+JFgbY65tKIQhHg==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:VK/JpQ==,iv:D7th0kgOsvGjp9DTQhATkwJvuF70iVaikXACsKX/ua0=,tag:qC3MEIk8bEa1aZsv+4gLKw==,type:str]
    DB_USER: ENC[AES256_GCM,data:UQutzhT95g==,iv:JwJw2WmsG30P/EIrTqjT5lOjURbJMBwq9yXIguZRg2s=,tag:FibPPkhK7/j1iMOUfLLHdA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:NpwwXJN8qI8=,iv:CVLZpV4bmdgHaMU0XzhxG8kXzmaeVMqdAhMXRM9FM2w=,tag:01ylXTqB44Lytln8rfXEGg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:25WJJBxtsE4VFRNINZNpyA==,iv:GnOiFbglARcKV8uxC4jYJtRlyYmpPaIX5WOkYqIABJY=,tag:WVAqFNM1tri803UagtwZnw==,type:str]
    #ENC[AES256_GCM,data:7C7BiMv58z0GHYNrvh04njxAwa4eJTXe9tVvuQV8yr6pIR2l7c5BL3DDjLAkQZnouw==,iv:tTkHpiWO5ibayCUnKqP7qfIiknWYqZqj1vnd/lFZiyU=,tag:vvKym5E+7F2tGCxZRq+TMg==,type:comment]
    #ENC[AES256_GCM,data:yi+RUdOrb8OBohMxU5hndjljRi9GESvXTOgFvcHzUhLwvH3hC4+ws1ZOfwiDIPR1eQlpKsn+St//KnKgYJ1dyJLlgJQAm1zgFPQLrXfwFwNW8i6mEg==,iv:sPQjESX9wBb5CyoFa4EFOjj1Gsik/vHP6Dibwr4sQiU=,tag:mAnVhxDpgq2oiy2Y7PCt5Q==,type:comment]
    LLM_PROVIDER: ENC[AES256_GCM,data:SZfoWLqMI6dk5A==,iv:klJWmrioDCNYsI80HyN9CMfFM9y60zUyNjLFeTkTYt4=,tag:+AY1yypzeym08tQXdRpLJA==,type:str]
    #ENC[AES256_GCM,data:YVgk9lWeu03x1BREUe8jDV7Tvn6Vwm+vF1TRiMD0,iv:z2r2kbCouobzXBnTxX0N7KOu07YrkpB3PpMllxtKYKA=,tag:0Q034ARpqWt3N1Sh3ABJFQ==,type:comment]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:jjTXAElkinV7FcQU8K6LI1uaxmnELbvjBpG1glZvhw1BMZorPkV+DGEitZbwEkSp8XO5KasOlwEBibZXG9qvVsIo00OD8KhLaA==,iv:9ZODTp4+iett5F5TZlWGQX0wZJylc3zdBmVKkoRdtrU=,tag:rwRBU58R2mBch7a6fXbKOQ==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:3RLtlvTernSRBEfD9val+vl8TNO+tr3hTpkE/lnA1Kkf,iv:R0L9dVyrRlI8aGmr1HteEhk4SU/udebWZgFwc7TwP6Q=,tag:clPnw7fxcS57U7pFPdmUcQ==,type:str]
    #ENC[AES256_GCM,data:xoXiayzsRHGUoDvezLE7TqZb5sjwLoJaBm2w2PWPXH986hpr5WItEXzrIMGIgDpUoClTf/GPy/qvskA03M/JB7kHvZ3/24dlY9rfryQVH/Lgb7CsIgtoqw==,iv:Yk4/y50XDXiG4auCytOtEqs3JTRbtHAMr2qq/O0k7Aw=,tag:QqcmqbkQdFIxu5gD3MWycQ==,type:comment]
    GITHUB_MODELS_TOKEN: ""
    GITHUB_MODELS_MODEL: ENC[AES256_GCM,data:Z4Emeb/q2E5rfv2g71svEpSEQFRoNaVhKDU=,iv:0SysGbp1vj5A2d1oTvFbF/KgFCT2d55Cf3Bz2QMJQnw=,tag:de3n6gktsorlc+bclBBPrA==,type:str]
    #ENC[AES256_GCM,data:KkLRpTMDi3XOnB+Nu5jlPupZMMWfXcFg7nSUpLpumudlTlo/LgEG4pE=,iv:8qO9FyyDvjs3C3/Rh4dGRkEywbp8w+i13fW/6hAR/CY=,tag:cqCfRU9sNVWkoZs73YPMJg==,type:comment]
    GEMINI_API_KEY: ENC[AES256_GCM,data:sdXtqVWSB7V5NGzgSuydpHQSDDTikD9ZDZZd86JwIS4F5LqMX0+KiV7tSj3Mt6+2KzSWdBs=,iv:TJIp5UkcgsUOPApAHYAs02Qhze2nNwI2JUryNFKg63Y=,tag:MKTQaF/9A3ZygR1cxEmH5A==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:ccdd0MYO3aRC+FstQW4LPA==,iv:FYilvzq8tVXPjyLQg2s3PMPD1s1AzRXfvtSqzmupzZk=,tag:/IrlUJYvQ2Bel2hnpp6H7w==,type:str]
    GEMINI_EMBED_MODEL: ENC[AES256_GCM,data:+ba4gMwf7QGxcswBm42cklBM,iv:4xaojC2Be6wvgeJFuMN8pCn/mr8BaGM7nB6GG4B0yL8=,tag:c/ct1tJPrc6PUE7uJGSXow==,type:str]
    #ENC[AES256_GCM,data:mRdsvQwFk2Ffp4fGh+ouaLYP8uZRwjMnN538u7bi+wmgDe72tw7r7bn5VsV0gTe6WsFMD9We1ERashom+dBDgICHv9w=,iv:1Q7b9csGIkL7d+ImCt5FTAUqXwEPUgdBlQaQFT+Fmn0=,tag:XaVxECbBbIrLnO4Ooegc1Q==,type:comment]
    #ENC[AES256_GCM,data:yngEn+xMLgUYE2wqLbiOkbl9cQhvNGxUxsNWKB+jhC46bHuAb4OIAQ==,iv:1ptm9Pwps+TtooofzQPF8rIkMISoq76U9W3k+IbswBQ=,tag:REOePcD/V9Nje8s+LoGWPg==,type:comment]
    #ENC[AES256_GCM,data:hWUKmo7eNUuOuRXS3/M65r99mc2TwIc=,iv:E8IQlAueBR5uJew7FK+S4lrkBZYkTVTLSb4wjQxDUEA=,tag:E+BWeG5dW9YeW0zBi2KP9Q==,type:comment]
    #ENC[AES256_GCM,data:Qse25RgY00kjdGGUPn19/0fp6j9Y6x541OiLRA5KP5UnNtiGFg==,iv:bu2QYyEpSi/rpG6jctTNaQK3WqlGV3GoefVElcwnWvI=,tag:Lh3ja1uce2NCEJj0WoihdA==,type:comment]
    #ENC[AES256_GCM,data:K6Jk6LzkMPynUg6Ohi8mVPcSfoqoTfXah1ycSM1LRcgmwA+WwKoekoYkmWyU+kCZMA==,iv:XbPqfHjf9nSQ/C8HLpGldM9CTVao2Cj+E2VYsGUATEM=,tag:uLT+NwlT0mctRDqHne8ljA==,type:comment]
    API_KEY: ENC[AES256_GCM,data:Q/3z+R++PMZqPcVS,iv:6cq1TONrwfIJn5aCuq/QUSbeAdtjDk0T+nKKXZ9S2/E=,tag:/E4hxaD/w49SVSCzPTjivg==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:W7GGxP1SMk/rWOHi7d5rhchWTPMCv8yDzAiaYRkA5o4=,iv:boOY5/3U8VwgR6t3DAPX7MU7tjayELHd5PJKqgBN5zA=,tag:0lpB1JCSDqnJI73ky2xszg==,type:str]
    #ENC[AES256_GCM,data:NHk6WOa3m9Q7hokXoopkZEJhXsTxuOXpjv+MdGQb9OTa9B8iapfyU/CK+L727rb7dAV2O83fqA==,iv:6bNH55N47q6n20S3TFrXVbmdGHzxGCZoKptLoyNd7mE=,tag:/W3ODg9Kog10HP6SgS2F/w==,type:comment]
    IPINFO_API_KEY: ENC[AES256_GCM,data:nsLGi3XungRDlOeNGVE=,iv:wsToJUM/41fhvliD3z2KmsWFK+XB8ARlX3Uhig9hcAw=,tag:ulbYlePgz/ukrIpqI8XQ5Q==,type:str]
    #ENC[AES256_GCM,data:a2MKXMyH44/CAWSmc9YXZXg=,iv:J04y3L9ZbmW2bvPVVA8gNICZo2h+BlJm4DwxN/9qDtQ=,tag:1IaftflArCanDl7uCIppDg==,type:comment]
    MAX_FILE_SIZE_MB: ENC[AES256_GCM,data:C6U=,iv:yGJbRYDZoHFFHL8WnaLTJcNIjemnS8d9DU3zzpGJCf8=,tag:6lcLbMAXKvijLvx4tMhTqw==,type:str]
    MAX_PAGES: ENC[AES256_GCM,data:ggsZ,iv:Jkf4PlzvdW9Ai3b74nzezBGefXX/8A7SQolwDeigLGE=,tag:Fm+jF0uYl+YvBHztiMjEsg==,type:str]
    PDF_DIR: ENC[AES256_GCM,data:qIhntA==,iv:D828tlpbTxdU/DfImxE1qFutJDlnoxE5bkYIxb+kA64=,tag:s5R+mkLYHsKrlJHK2w6/Cg==,type:str]
    EMBED_BATCH_SIZE: ENC[AES256_GCM,data:oRw=,iv:GXqak9wzuOAIYLOS6iT6UbnNk3B9bYP+yNXr399yM94=,tag:xpi+00+l6pO8LjZ1e3vEYw==,type:str]
    #ENC[AES256_GCM,data:IDbyeA5dEjNFbN2wybrsRKI=,iv:geA6R2nXZBBchK3cQLPQpMNPotv4ZBEh9UY2q3ztPKs=,tag:9HDn02vg2i5pbGBYePG0MQ==,type:comment]
    CONTEXT_TOKEN_LIMIT: ENC[AES256_GCM,data:Jv/6cQ==,iv:XGvAggra9bmlBV3/dk8d5neVoZdPi7j1CKZu4fSFuoQ=,tag:GxL7dIHOTU2Pfnwddh8iWg==,type:str]
    #ENC[AES256_GCM,data:6HUKitY=,iv:+CsLvrYy8bSqSWuvlKP3df+LhQr6zW389HY7Mm2ROiI=,tag:8uCnCNLp+Qk1RGq6AKiGHA==,type:comment]
    CORS_ORIGINS: ENC[AES256_GCM,data:IqNZc92QhMDpZ9FerntVbv1FCJOHLKcyeN9Tcy9qLMnLWq93hAk/PyZpVNBETBTjjjVetea75afcqdOZvU8eKXitBjAvJOOfuD0Cy2d7tCjIyHzi+bkih3dZWVu8pX+ggMr+twHSAKi70BJFN6zRtVF2h5EJZaimNfkHcFI=,iv:PIW1AbpIVWMOx5VVZb8YHgnAXZSBmD/hBGfYxGbx3zg=,tag:/lCzep+aImkUi9eBPRj3Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3anZheEZMNkYxRWxDdXpT
            ME5tdDBiTmNkTHgxZ3NIVElKZWpJRFFWTnhnCkxGZU9IYUtialFPczRjZmdIckZN
            MTU4c0NnSTBrS2J3UnpaTnJKNjNCK1EKLS0tIHRReDNUdjVhbzBRQjVqWXd3dzV2
            dEJFYmpWaEhtc0Rzek8yb01UaWlza1UK7h5supHhyV1lsBl4668NQKV2Qdgn0Vyw
            KU9v6C+Gdd4GPp8MFGJREv5JkmC+S4R24L1eCdIrItG7waWD76z6UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T08:03:00Z"
    mac: ENC[AES256_GCM,data:U5izTjdrdSWWwf5yCCbAukZX3KE6UmgoWYinmQ4VPteeaQKpFbwSuOEue9Uzo1Mpmu7osTJqbSFiu8GGA6het9ynROqtgbsWLXB2OVCx3tVcS2GkpWQ0Ts+/eWFJAq8Q8sHBHHmAkgS1bwW+/8IYRdUEv68/pUTTJ5BEy8fUsEQ=,iv:6TwVyHCgVFl8DucnriBFQ5F8GL68+pF/jxjKcEV7/1c=,tag:raNwYVNMkko+HiOo0keyGQ==,type:str]
    version: 3.13.1
