apiVersion: v1
kind: Secret
metadata:
    name: chatbot-secret
    namespace: default
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:Fyy2NQ==,iv:vnCjXwHFtDzu86xXftKjAirVoXLsR/XzOY7qk1gnPNY=,tag:rNOkBww4jx8u6K8o+kp++Q==,type:str]
    #ENC[AES256_GCM,data:58sprJaaTw4i,iv:Zae5j+QzpQWxXipff9aW/AEXJHRz84evraZq/yN/mW8=,tag:Q5A45lfh6/R06uuwH0UglA==,type:comment]
    DB_USER: ENC[AES256_GCM,data:+hHqOrLr3CI=,iv:jkq5CFYD3jP88T8HhVHA1fbpjrpo777Bnpm43lha8BU=,tag:9jsEYHMO/P9q/W28jVVVxA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3lbEk9j26kg=,iv:EaQtCLe3chOXzQKKRLLnwHaV8A9ZfiGaqebtYYveBYM=,tag:3TkQKCjTlbd4fnN1U3+Cew==,type:str]
    DB_HOST: ENC[AES256_GCM,data:EP6Oq3VRpbhl,iv:/maONBGxnuw0vhlDM6W0VCzQ13KXNpWCyHYxDFsOEa4=,tag:i/kEsAK5miA5ruzmHr4//w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:KGeO6w==,iv:p2QZEA/wDtFbrvIczK3bwMYUnDMbNhNZsRmuuviV8nE=,tag:6f74O7dd6ki8QlcKRUBn/Q==,type:str]
    DB_NAME: ENC[AES256_GCM,data:+JeatUxmtpF8cAgh8IXGOQ==,iv:gCQW8fM5goZuArVEATlOL/EILmbP2OkuCzam2R0/tEM=,tag:5TTO30+uxaZPWGBSwS2/gw==,type:str]
    #ENC[AES256_GCM,data:DhG+vUePmOo/51bXcMH3tHXCViYAlI7hUGmjqoB2RdAmgueetaAU4DGkJJX6C9aJfg==,iv:o/q7BNCHt4ztFQqK1OyD38r/QYTl13S1ggEuZLBlWXw=,tag:n81qE6oySIJy+UVrZMWrhg==,type:comment]
    #ENC[AES256_GCM,data:y6WCjYZZ21bAni0J2LrStaXqChCBKKYFeerk9vo0lcYH3+BctG+6u9f65QC/g/0yNmDd0LjU0ODVW1w6qa5SOpVka+Ev4gMQ1SjiUdgaJP8CRBNV6g==,iv:Fu0vakbBUnApcfE7HFdEMXKfe9tqmCXAsMUz1pGZfjQ=,tag:lNXECC6gITIeKMi03yIotA==,type:comment]
    LLM_PROVIDER: ENC[AES256_GCM,data:qQm0eUjTPxY47A==,iv:1Gdfm+8f4EI8tqr3XKEqv3Q3ljJtvRgqz5MsiLIaXBg=,tag:60bL5uLssqhszaBV72AU2g==,type:str]
    #ENC[AES256_GCM,data:aa5iRBfagh+3N9FA0eA9YLzI0l6/R489KKJqD3gH,iv:w4EbtazD9g7nef7st8D6wfqSHXVuiZOTRIWmSlbrhEE=,tag:gGqqdl1rGz+53zHTO3CjRA==,type:comment]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:fvwb7g3WxDobOE6YpXFjzHaoCbakzM4XiCDwNgvf+fwOlzghbFyOhmK3cetIZzWaAZZFlO5CZC1CmeNxFUln/g5gqFmI6P0Tjg==,iv:A+lHEgbC3N18DItPma3oVRPwdTqpAsb28PrpEAki2vw=,tag:2LWgaElXOzUzlD6cULejZw==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:n6e9vBla9Z2+dGP0YbWS6HgtP/6SWyCSsohr0px0El6t,iv:APncgGMdH3Kwevx9OBPUkODP0aUnHWTBUb8gH2AIs6c=,tag:7fXW5ddFlEIMo5Y2rFcOdw==,type:str]
    #ENC[AES256_GCM,data:cUnvsc9agBL6ddlMw5rq4abRuz/RapaXAiVgeZJsoS5JVFLYvP4ok5BhQlUBxlV9CacuIFE5onw4Eqz7mHiyPHS5mvqmDRY5UibKNQTHQGodvt5C1NFrlA==,iv:KlrLQABMTPBNvrOW0SeYt6hGFaNsLntY3cSBmsY9CWA=,tag:+JM8GCE+eyQv4OqVYB+viQ==,type:comment]
    GITHUB_MODELS_TOKEN: ""
    GITHUB_MODELS_MODEL: ENC[AES256_GCM,data:tbL7PNx+9HO+PWIL1GhyGChqJ422IShoYcY=,iv:OyFaEO8KTlHAU41lgY9F0XcjAw+mkLLtXu/LMpFvteY=,tag:vTk3umK9kQiSTOtFGWaeGQ==,type:str]
    #ENC[AES256_GCM,data:XCxxlVZMMcabAwDU5TQ1ldf1Zd8mJvVbZtCWd2T/1inz3eS4OuKJ5Hc=,iv:YjUoHUmf+ukWiJd7LcKGfhqV29fJQ9NrGAzKjk++WH8=,tag:8MSFp9unm6oXq5kMi4vaOA==,type:comment]
    GEMINI_API_KEY: ENC[AES256_GCM,data:u7zNKub+dyw4eFtjYcBGVSIGu+HwLUKJyDOvcpWSGd4Dym4SIgiTEcrHq/e7jVsTMZLS3J4=,iv:OJLopt6lH46k3oUF+1pSm9xcKDHyBWa9ddjJ6EhfAEs=,tag:Bc9gj1qr7YgkQPKYdY65Pg==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:JfrKc9zqB/3N20NOUEKy2w==,iv:zszYcgCjFS1cgSuIoW7sUiHcka3gfORHGzng/pjCrqI=,tag:jo9ade9PTCoXbuYIowLW4Q==,type:str]
    GEMINI_EMBED_MODEL: ENC[AES256_GCM,data:6y0zTS80StNuzazQiX9Tjuoj,iv:a5LFgbdcEhx1V/qRX3o/Pk8oO1QUu67oZEHvF8W6pSo=,tag:ddGDVlbWkVedhElz8QRFcw==,type:str]
    #ENC[AES256_GCM,data:inMdXyE0dOLzcsHMs1vHa5sxmRLOWBWCaik2UMTT+uAI7IQQzpS/S+Ypf+59Bw8D2MyZu1U+5MJmtuzkDejOO69+hkQ=,iv:dN64W1TITNFtYY8+Fuk0tmBiwFqACQ0yG7HrN0WVz4c=,tag:JbxzjXzfSNylvgyurxaUrw==,type:comment]
    #ENC[AES256_GCM,data:JHi9wall+WTCpk/3GTJ1wkq6kBETDCRshFIblB75Nb1V+6Qp6oNApg==,iv:SaioD/koMzdEr23XdjlossIqhwxMYDQjx2n7yN8aKUM=,tag:zrroncc1Z9jZCtgWHMkXKA==,type:comment]
    #ENC[AES256_GCM,data:MPq6DaZdfUJOF+jC1/Wf3o6vQyLugbQ=,iv:8Tu/du32WA/lTCojnk2E1nVUk+qRgO0zLlohOeYGsSI=,tag:h0mkviyXIFa88/JF24rsaQ==,type:comment]
    #ENC[AES256_GCM,data:Ktvq/ZH3+weXY6zZEpSxOL0gEq15+x+JBpVuGYcZEatj/AT6Bw==,iv:tqrBuaybDppiqMYgYyoXxVIEHDp3G4EZooow1G3m2TE=,tag:9o6QnesPJv8PC/Hggu8BRg==,type:comment]
    #ENC[AES256_GCM,data:joxkzM1ziXdpi48M1dWVeOiaX3SvzYtJIN70U29IMOqPMzWRplfYLN/R35+bZfyM8g==,iv:RJ3oHIRhy3HE5aHi8SskFXTm9etbQwtTJS/O+QqVutc=,tag:+9a9TarJOqGgi4QaSJOsBQ==,type:comment]
    API_KEY: ENC[AES256_GCM,data:SNNHowc1MEzIn56K,iv:Td2NzObQ8eWJoxq9bbGoLLNvr6g27rVLq02fPSxdd44=,tag:B3xUa9RTSxaJr2PFYDN9Wg==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:3jH3z3yeMpjrzGSJ6p22Z7fO9S+x13LtfjS7ueETGPY=,iv:FLK+3W2AWfIHsalEEpu9V3F2J2d78Z9A1T4H/TEGRLY=,tag:DsN9d0GxEaHP+PxXsEJu+A==,type:str]
    #ENC[AES256_GCM,data:Y/SLwwt6tZazo/0UtgVp7rEH9Zb55wY8dyF+AzE3G3uP3J89BKyq1tNFaWWHBlAv9huCMUJDuQ==,iv:13FpfIa4VMHQ206OvvO67eBpZ8hPwTvkvcg+mIlezNY=,tag:VNvbs9g5sqEmU0RDw715ow==,type:comment]
    IPINFO_API_KEY: ENC[AES256_GCM,data:eCAhOTfDOe4FOKqr78Q=,iv:dC/k1GM9AUZVnN7QRvm/S8EEovoolaMHTMD0NsSsz0Q=,tag:vAkGc3K7ZTLiaNAMlQmFHw==,type:str]
    #ENC[AES256_GCM,data:qPP0VxCyEI/KPT+W3wL1exc=,iv:xgdotE56L+Zpl7UbyaSoOEetnSYWolZt/Lc7REldwAI=,tag:jAz7r1+MWoiemeqX1Pv5hw==,type:comment]
    MAX_FILE_SIZE_MB: ENC[AES256_GCM,data:0V4=,iv:uGrfwN3OyWqhOJo6v87u+ZvnqTlYL+og02Vn0aoUL9g=,tag:pHqPc5F0/rOfiG0YCEXjNg==,type:str]
    MAX_PAGES: ENC[AES256_GCM,data:Reb+,iv:9ARzp2g8btVgYkEQ+1NTuhLcxpmpPQ7N5U2GR3f6RuM=,tag:MwqwRdnh1gHZI00Xl4eYSw==,type:str]
    PDF_DIR: ENC[AES256_GCM,data:qBQ/gA==,iv:uwLkUVsVnQjWlAxumqh4lrx/A9LxFuySJfSvrpRyMdo=,tag:/dmTLF1+zPDcevbBSkB9Tg==,type:str]
    EMBED_BATCH_SIZE: ENC[AES256_GCM,data:SlY=,iv:7bcoqFfZyTx/qPayqiUg0kraCc/vFQExWBHAqKTmDS8=,tag:tJvSNeOHB7DntUHwHol1/g==,type:str]
    #ENC[AES256_GCM,data:S1u0BTT2S8qxB0fDvY9gxA8=,iv:gujTQFPDQZFnMTK9CZUxxQjiE1b6HdZBks5H49RmEEA=,tag:9Jbjv2K0pmza8sld6S9HtA==,type:comment]
    CONTEXT_TOKEN_LIMIT: ENC[AES256_GCM,data:c7YoNQ==,iv:Q5zFwWtsMA5VPly7ZPf+7Dh3KchCoPtuMR+KsHnrEzI=,tag:Nqy21q6qVfEO1oQEH1iQiQ==,type:str]
    #ENC[AES256_GCM,data:yY4iJ0Y=,iv:zw+80hpTzTRUAKamEh88C6CXTTbkj7jSkdHjnyeQTQQ=,tag:gioRJRwkA92Ya5qqOvbk7A==,type:comment]
    CORS_ORIGINS: ENC[AES256_GCM,data:EbF0GgIjXyjS8dajzV9oZrFHxh4sG/9oDAWIWEWmn5GrCo4J4jlLp6tjAirH8d7X8bpGuAmr9ApQIBsSyLuFMB2bVgxD5MSaOdyGS8chK3JhYtwtNjay5V0zlBkH6nhs6qgEz3sUoey10ihntvW7WxEzq8nFcBP+sqviRvI=,iv:hB9xV+giT3X2KFL7tiVg8upQtcHxewi0TA2suK6XzhQ=,tag:NriMgjNb3Yqm7PNmb3qZlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNkp5YmtSMmlZaFhEVjIz
            SEIzZGpFQ0F0aTdNajd2QmtiNDJsMGNhRDNNCkdlWU05eTdWWVpURjVlcjFrQXZ1
            L0VRb1BhMXFOVTFzT0FPWVBzblg2OVkKLS0tIFFyNkJQcW9TTzNXbVVQc3pPWmFw
            cnRiOTdkZ1dQVWxMbHRKbHRDWnZ1ekkKVzatSAojx4sU7auntBni2c2waYElcBqy
            aMfBLBKoTDp29fuQnTCTdzA9DwZCpUaNSUvuObaJBbFpdAP+IavYaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T06:14:33Z"
    mac: ENC[AES256_GCM,data:Zj6XBdoXy7L5F5479oW8FqyS4m7q+hOBuAQxVJPBuIjwF99il7NSPDXeqQGjsLdjnR3ewivCnCudSQBFWGL5QttF6Sm2f/hPFSqIqdq1GjraJfGCxbAnluZPfyiFdLRFLsi6BzAjoeom/2Uy0iiG716xqOfKhy3hPAx5dM05Jd4=,iv:ijjcdJrA1k+8V4AmzHdSFaPIG+v508D0ByaBfMQSSi0=,tag:PQQjqXolxCP7l5No+8DdZQ==,type:str]
    version: 3.13.1
