apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-weekly
  namespace: default
spec:
  schedule: "0 6 * * 0"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: zot-pull-secret
          containers:
            - name: backup
              image: registry.aashutoshparajuli.com.np/pg-backup:v2
              envFrom:
                - secretRef:
                    name: postgres-backup-secret
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
              command:
                - /bin/sh
                - /scripts/backup.sh
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: script
              configMap:
                name: postgres-backup-script
