apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secret
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MPQudr613o6zgphA7ipkAxZrejL6lSpe+Q==,iv:sD/oKkKjl6PpIMEHMSCRaV+5gIHq73+u5Osyp/BCM3Y=,tag:uDvTLr7whhs37T/El0erBw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:i6Bxq2Kw72lTgQBw7V5Pg0swDStb8i1KQIOehPHmxQ==,iv:Qp1ujgCjQlf909TKTc21BonFDOSgdCNC9H3VMrLbF9A=,tag:AKDn5GfPQuuh3YEuhQAkbg==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:Yg8zz6VwdGSJlpkr4lX4,iv:qrvodCbnowDSr8V1YFiYvDdYKcOAChBQku4lWK/1f7E=,tag:CrXhbggKxbXAMvKTUiBRbA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:KsT3qqV8qYJQRhV9P9dC9V8yQLohFkPqjIwKZb7H,iv:Iw7EGj2T7CVESn1xDXZZzZwq64j6e2OF6PZtmB6KV+M=,tag:CT0ewhsqr5+1U2L0qw0tAg==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:LzRNRbc0JeiICGiwvsLWZEv0NiUpzPZ/mlONB49ir0vJYip5GdLPlJW6HNuR5gt1nDxS0cM5HScFNGARS9440l+uwJBKJZQ7yN0a5EO6u4jlqszjC0vbg2LJ8/OpHfSahXOUWZzzH7SvNcBhDACVtBKxU8O5orGJQw==,iv:mrTAq0Kjf2+3abrz6uIbK/7De7x1Fdf5mu71luIOc9k=,tag:xNMKiibpqBm7vxf/2iKJqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOKy9wTDdpSUk0ZVRwNW1U
            anFVM1JMN2RqQUFHb0IyOWlsMGR4TEFVakQ0Clc0cklhSmFleXdVR2FvVWhmSVJw
            eGw2bWxQa3c5blZZVHhHS08rQU9CclEKLS0tIGlTQ0src0JWWWsxQXA0dmQ0Q1lL
            UTdPVER6dTZGTWNTZWZhWkROYUx3b0kKEnQ0cIa343Mx/ydQy7mHeBMrParFwSU5
            UTwhKdg+lsSkvEkNbmbKke/JCXd0Dg/bFThTOqTUF786yem/yV7J5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T09:11:21Z"
    mac: ENC[AES256_GCM,data:jl++AGtOce4FiV0R5RmvGF+i6zyCJOaK7AcXPOpE7pm52OrZ2I0a3Ph1E1d5wbiquYMGcfw3w0U38SWnRnjpe+SzgBYB40zOdhfebt6xBpgx2bMOnAoOEYYv2QdEJlQXpKKgx1GX3aHrSaiW83JGm9gd6zWbsp1MWj6XCXspmw0=,iv:2uWEblUtsNcYnLIJMRcg6QrLkvmCTvgiPoD54BvQCxY=,tag:l+ROIhXPZ5xQe7KhEA74SA==,type:str]
    version: 3.13.1
