apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secret
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fi11jELiPtjp3sZ+GDWdMTXA9gV5jW8MdQ==,iv:qBBaWMhkonGGt4QVZtv3w3UVQb93Xhmk8RTBqda9oUY=,tag:87viSax2zwI/j/eDRUHFbw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xr1yUXOyGBD84TDezzOEebT9pO0wporGCJpOMARBfg==,iv:H3AauyxOiRlsPuiYzBHhVfEAeNZ1B7dENnGHyVToav0=,tag:+2qaaNmE7EcnFLXLPGgszw==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:JThzSuAwyvbgY4146VRtwQ==,iv:1HjEmZ+sC2dG69iuQd+/qYInskogV/2NAJfnUiKIPdY=,tag:FjVWxnciWR9nHEF6yyNTUQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:AccAQLmyGlyHzHJScjolgPognWcoNL5UOmLw3Y++,iv:SZAjUvzdpwo4xZGym8dBqQ2Cu6emxvs/HW5nf3Hx7MQ=,tag:lTGQf4A6P8hFGWBPBWilaA==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:vRTKFOQ0ywZbIgHkJZQ9IytdAWkWZH8lLTYxYa5oHXDWQPFAexH7CKTq0s8/htb1m9z6qvIpU/J36WQTl1hcPYSlcjPaqWNAYfiOH6ijutiXwHJHP2s/8c+FVevpxotzSR4REoBqodYR7vTivwG5LHRKd7Eaj1iRXQ==,iv:wPu4/jsD0RWDa5cuJVFADSnWgoBt275mqlvC4MpkYkg=,tag:omTSDKQdSAnzVi5ohQWYgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByejlPZGhxQk83OHlvU1FL
            elZ3TDRxbVRiWUNjcWFRQSthbjR5OFpMMFZvClZyWEs2UFNHRlU0OHNhZFFyMElm
            NUVDMm9wc0c5OGpGVi9wSVFYVWpVWXcKLS0tIGowcFd3S0M5MlRzdkRDampQV1NU
            WWlrTE51bUZQWnM5bytBdlhBRitqbVkKKW4zv5LISWw3sbmkCkThhIhK9qFrBCh8
            1OJmEUZJQIUFbtpzG7qxMHigxCOZYrWH44GGuGL4GkISkWBawjF90A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T17:17:29Z"
    mac: ENC[AES256_GCM,data:qZqbgU/fF+vhFWJdnR/JAjlf63Vm3Vw4rd0SV0VQO//MDDKGt3ZXkMKDyJ9gZ+ICAN6BoUr27R0YQQcyizXT0QHXk3QfEmcgOop12D58f/x//3bg+SQ/C9Y95+om5hOZJBBj1nP4XF6SlcUoF2qmhRbKAbFB2XKpl2R+/p8fYvk=,iv:507fZ9O3We0Ptr4eiwqBG8+bzUsOpL2RYMfCyYzTGDc=,tag:ytPtXl54q8MaIzAZDknZwg==,type:str]
    version: 3.13.1
