apiVersion: v1
kind: Secret
metadata:
    name: pod-watchdog-secret
    namespace: monitoring
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:bIDZOiHR3rXRioe3+J9/2Xg/RAm7i5m8S+Q5YhBfNC/GZvynTpvW0UwiQUNBYsO0dWuPTUoFU68bRi+Pzx1ZLUfwERLGbSD92xHUvAnidtgxiOLDBR4mkZAImtojh/2BerkH5DWNzTVJZBckDt+M9qyMRC/a4wbjzA==,iv:1TvG//GhU+6fslgUhVqcp+4qOxstgwgnINRIRWl6kBM=,tag:LkZf4u9TWO0rLhfxpzihJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcUZCWnE4dllCMW54N05R
            bXJWcEE5aGJuRnQyb1k5Vzh0aUVBazY0MWhJCkp3ZGMzb2NkMUptNjNISGpENjA3
            bkZRdVM0SnBleC9TTlVjY3JLUUQ3dk0KLS0tIEUxVzJRcVR5VHo2U1FneHZCa1ZF
            bHVieXhVcUlwU2FYUGpqN0pGcVk3b0kKFdTYnb3CbzvAqHQ/8thdK6rr7VQ2B0PZ
            6GI2ejvrx3WDL63HHGeJ6frQ7R0aznqPes2UPGIHDCpmNBDB8uIXgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T06:06:50Z"
    mac: ENC[AES256_GCM,data:ZoAGGp4EnDNNrkautZwTI2u4DVGRkIDcLjfIsrXV3m3reZWPB+ul02NeS2RvAKa8DdgTjbpxZTLnEMLk6LJtu3E6ZaR76FczLbOU0mKPc4RiTlqn0UWK3EQknUbdd4P3afdD41HleaqwMM6wHiFzKuHZ18PKAY1DPJyNU8c4wME=,iv:RDT84vySEEi9nXEX9m/larzkzpcNovf1c59+2aRTIWc=,tag:Bt2yxSU9U5V0CrhjiO9iww==,type:str]
    version: 3.13.1
