apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-frontend
  namespace: default
spec:
  rules:
    - host: portfolio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-frontend
                port:
                  number: 80
