apiVersion: v1
kind: Secret
metadata:
    name: auth-proxy-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:YvZnTeAnDLIQ9pJtbwcm2UJ+qwpPRxfTfj45knctXGhRIg4MVUsUwvxLoEhi8F4RyQUAylWdnpnpFfmxz41xCicaaXupbhQ9u7ddODT2rjCbwmFQua9X5bx+YdPJ3zSmLPl/dPAngx4OZsR4lA6cGyhG4ia9u4hIKCoHHYjdopeod2PeTSS0QYwJpPZdtLOQbddAIcrbxKDr9LjKNVxZcl8yJOaHjcnRaUPYKbhzJpUlEnTh8yaoV9Xmfe+ja/loDSzg,iv:iGtTL+I3p7xqhvLyPIcmPLCD/WqmHFRVbaaU47QYXfc=,tag:mnTw+SuN69pHtuKDrDiKpQ==,type:comment]
    PORT: ENC[AES256_GCM,data:vYc/gA==,iv:qrubYxlqy06s3HKMpDRITLMSzqLyiriD0f96XolBvDM=,tag:qMUiJqcnc6joexhcxjWn/A==,type:str]
    DB_HOST: ENC[AES256_GCM,data:OJ159ZnS/Z7M12bZuNUkC+4hKEN/xn6JQ0kQORH9WWWWhA==,iv:ab/AnfshmOlpBYiuXK4LkjTBkVniOYVTW9dimAwoHa8=,tag:KMOLpwECEscPgvl9BvVocg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:nBWDig==,iv:/7yNB3xqBpidG34F2zTUx49A+Rip98J3OJRv101L/qU=,tag:UKpvlZ4fsE1NoPtwCjIQqA==,type:str]
    DB_USER: ENC[AES256_GCM,data:6L3Et+gzsQ==,iv:K4ClMRuzLZDqY1Z/Odc5eaWaZnkgqQfA2AMySNaKPDI=,tag:6Z9rOOOrmFyNsk6nySmweQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QUbZoIT9ofU=,iv:rHq9dOdLvDlOlbd3NLGwiSsJlwn5jINw03hZ4eMcwYU=,tag:/4VaB66de2edKs/Z+oBzXA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:nXwyoAtrd0wg,iv:jlbwqtnn9OlcUA3HIHQZB1T6HbZwoYXZyTvwPuZUzL4=,tag:uIzA/TiR2YFqLB1o65FTww==,type:str]
    DB_SSLMODE: ENC[AES256_GCM,data:e7xWx3zYbQ==,iv:JeYYOncujWkSiji+KJ4aPz8s8NVvRR/cQOMsNMAgDaw=,tag:QMFRcHT/aNzUVW+RIbhuFg==,type:str]
    #ENC[AES256_GCM,data:QLg1WYgkqjhyNYWcRy68Csa+c7tfZasjk8qIF/kZCjwdPstvqp9NDd31bPsal+ZK5BqptjXsYurqEOiJA02g6m5mXDMlNQ3QP7yutybfhgX4oXRmLX/1X3T6V/WAaY2lTzGK1jqAyumXdzrHEb2GIZ6TlZKJFplFOGngYMSGGsyXKG2kQUkhOkWRQ7jEfQRkL/yDRHGRWs0SIJ4Crver1T9jyTp+UTOgqO1qBROqUCrOTvQ=,iv:mNqEFU5kP58VWgLr3m+8JtA74t5LUQoz4cslHGZjG7Q=,tag:LiM/UsT5hwv9sEv02KVGwQ==,type:comment]
    JWT_ACCESS_SECRET: ENC[AES256_GCM,data:oH8c9UyTLCu1L58U7LaFft5VIVOVGnw49uS+M1tjqWsnUVSMhB2DNPOMN8XX0JG9kHO69YfP0OmG0zdXGk8oQQ==,iv:s2N3ENvNG9wqoA6jWn9SpDlfIRASWKGEi3UX7zXSiR8=,tag:3X2D98sM9J//supd+teGig==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:gB2rtrGyPR2z7BrD4A/YU1ZmLozR910ADgn+fWyE+kjLYUi1ZaN3fpsvRl/eYzgNMMfb0f8WZroB/pz29Zaqmw==,iv:3zerl1ho2iN1LRAKkVOmCKl/Rsnz9MHpp8uaHoiVO9g=,tag:jlu33aSmjR57s8OfrSAxLg==,type:str]
    ACCESS_TOKEN_TTL: ENC[AES256_GCM,data:MGIp,iv:c05hKgpc6IqJc3LajpbvQHMkTFFMbUyErNPCbzzbsdc=,tag:dUdvyeFTu06oVPFSkSFUrw==,type:str]
    REFRESH_TOKEN_TTL: ENC[AES256_GCM,data:GFesfw==,iv:ORr6zJ8eNFZ+ax8y2lXjfYO7drA4Iqe3IWA8xegMOPo=,tag:v0EJdbfLoB5a5JSuLBG9qQ==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:TT5VcTjE8pyP7GgyaynWnCN5fuhJeJ/zJw==,iv:tTSa1Ftc3yH/X+eN+MNyJXd7qAbtyE2skxs+LLLWm5E=,tag:ied5QdXU23A47+G2S8d3iQ==,type:str]
    COOKIE_SECURE: ENC[AES256_GCM,data:NxMGBg==,iv:6xtYke+Gcnm0SjCaYcNgI0RvXxV3ShKynzg2lcVXTLo=,tag:8mM1Ee0xpc3disFwoPCilg==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:7ghydcHh57yQuX4lvqv2e3+/8qlClbgdTjWjuBM=,iv:Z4SetxhKxnCAskig8nV6HR5mIxtUJ7+EHAoZtl/Ihis=,tag:zRlm3lhaQnTIqXrnnon+6g==,type:str]
    RATE_LIMIT_RPS: ENC[AES256_GCM,data:Hg==,iv:nggqC4E6iNM5ja2C0rmnEtXy2E+vgrdNDezadcEz16s=,tag:iQAC1QhwVK9yIAXyqtAVFA==,type:str]
    RATE_LIMIT_BURST: ENC[AES256_GCM,data:Xpo=,iv:BH2tR0F3K6YfVP/D0i1xlaAYq4L6HHQANX48kdsJWXk=,tag:M2NaV1BUJKOaXDZ4O2lU4w==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:PUnxtbrUNTiSFftLBkUP3nlaT0w19GFc/yYJ4XdRcQ==,iv:dn+XIZt2hr8jXB5nrGT80NrNRhEQR+7Lagipab+SXsU=,tag:Sy0i8KKcFCA0VeyG2HIGnA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:kH6YTg==,iv:dteUR5LB8Yx7dtAewVzlGXs6P2L5CtB0a7FZcoTJ4e0=,tag:NDcicmptDDwsOVKNAbM0Pg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:xH09hlExSac=,iv:WZ+ADBGiTioXJaX11K/0Rk583D/RQY+VN+5Q45g7fHM=,tag:bysSGEi3NaPYCpvdW26yMw==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:wg==,iv:zdb3SQg90moxaVTMeLrgvOdiLVAxTaLvDMF88MyOZXA=,tag:dFK5GIsEhdk4ec0n0SwcKA==,type:str]
    SEED_ADMIN_EMAIL: ENC[AES256_GCM,data:sFQAbeThZnI03GHhW+yIs2mHsQXHsRp87u7v5LZxXKKOEg==,iv:zYKN+X5APHPomKaVNhsdRuDsCWpPXeMRt6gNNRuZyac=,tag:bRi6ADd30Dovw01irVQ24Q==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:iSNfG4RH7xuUy1AeI1gButQzl2tG5E0=,iv:QDMuOJs65fMJM550Ze3KXhGv8KdoGT/GBEWoD74INTw=,tag:xiqePKoXJsJU1KCQ83cTUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROHVSQ1dpdWRHdGhVR0dW
            WnlJUDdFd01HNjZSRC9xT2N2UHZSLy8wRURZCjdxK2hWOTZ6bjBydEwwRHBMMmdX
            WUltOHR0VU1tTS9XOTAxaWdPWUdtOTgKLS0tIHU4Qm52Wk0rZ2I0d0UvbXFMbys2
            SDRtbElFblpCekc3MkpIdWpoM0JZb1kKHKY1lmYW6wj0wPpRNEYRaDWEf8fLVg4C
            0CVLrdsCSZzxsme/nsR0pYzqlsFC7Mk0cOqh8t+HSx45GuM0hhrW+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T08:41:37Z"
    mac: ENC[AES256_GCM,data:VnUFINg/L3BAJmfMZIcEEmM6L2FcxLcsAazSVzcnyXWVjnmTR5jAFha4AEorSbLi1eZsZ6OX9APES/GPbO+gbtkH003xkPZAwznh5YuVAo2cPrZeYGoOWfHYAu7UeDZzgTOOt7tcGcA8ed6SxSffM2o+/oDyuPtNySZ8fqsZLdU=,iv:AoZAeFOLj/4Qzq5TCvKkaHt4JptngByuJ2/P3z1oEMg=,tag:y85gtUY3UTguXAoAyA0e7A==,type:str]
    version: 3.13.1
