apiVersion: v1
kind: Secret
metadata:
    name: auth-proxy-secret
    namespace: auth-proxy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:y/yyUOYpF6i+y2b2YsRvYamywUM0VAIhp26Z1iuFSoyXqF0TjYk3q+hRPaS4/5PzbqIW5p1d+u9nDBuuvJ/aSeGza4P4ogcG+YY4OvGgi+Rwk/xMy5r23QVGyhz4uPLnA3k1xb/UJi3e0TU6EkalJcQ7YtF1CKVEGu8d6PCeE0RPJC+Cjakv5Bg4Pxuk8jMEdvdTqDfZe1W4S8pylsU1cRQegvxi1YZkAtyeZ1TzB8k/WKQ3w/+HrZRR12w18m09x8d4,iv:6PInuLfB8A3T9I06VLMMxPEq1kDY2WUkOVcL8xvggiE=,tag:oDEA6ymunZ8GjJgHAOTtjw==,type:comment]
    PORT: ENC[AES256_GCM,data:AlPoBg==,iv:73CiGI1R/gFbf32MgcOcEarPisJm5kR7hqWINwNJ+GY=,tag:6R2X17gPf/r80P/sAZGMuQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:2yAAMiUl8ECG3kAHsxm8IFxU3/neWmXWtV2wWRq9h8ZVqA==,iv:LXdTxKRQXGA8JMjcPnLreXCs8uLN8hh1vtby91caApg=,tag:mA9mGypPi3ewERjpSst+mA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:TDpQyA==,iv:1IwLJguh4GB3qpxfQfLwR9JtCXHCqZlAqb6lk1f2mBw=,tag:cRpsRUpEthjYokPEx61bGw==,type:str]
    DB_USER: ENC[AES256_GCM,data:A6eHhxzrEw==,iv:HYVWNW9vO4vz8UJAtIap3R9gBizLabEZwhYqsln9aIA=,tag:ACOe8DnNzVRIEIYbNdKDMw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8Z0mPrRiscs=,iv:lHNu6srigMCDg5Z9jeq1HgSF8QEore9KEWX4/NZfQ10=,tag:b3AKeHbWZpIARQeQvNn0Cw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:r8+qZDOWiPb1,iv:AScWRYB/zt8Rawl+w6MU+1wLDLW/7rvXf5MBxjYPJSg=,tag:fyU/zTodXv+5dsZCHcpzXA==,type:str]
    DB_SSLMODE: ENC[AES256_GCM,data:DkAMcb619w==,iv:lw4H+ODV309DueEdP9b7nKAbU677AS82mWzmSCVsszQ=,tag:TcEIO9vG8Vdxez/UzyW/Pg==,type:str]
    #ENC[AES256_GCM,data:gEjuScUOrb5aisGd/+IkJCOUHA1lMCqd3upvfUokBxXvtYocGWda1sNeIRW7qXjtIhMTtQ95O3BBBWkyzg66hvPb893CFRA46HcEWmhKY4amVK1OoNiUwaBnj6EJOlCv8vzGjcVrS2Q/rTLJ+TtKEE4qEDwdku16CVB4LrECf/U6PFMRQvvmUUEjq4RbC+6r7IapfY6FfXdoVO2+MTA/6VEWDdGh8RC/NL5NvtaUzM8zT2o=,iv:0L1+T9DvWWDOOWRa4UvT8U8XJFB55yhwAmwdqgg3Seg=,tag:1bMdGWA+CeQXdZZuX+wuig==,type:comment]
    JWT_ACCESS_SECRET: ENC[AES256_GCM,data:sDmdpUio1RHFXqQrp2DjlrzKo5S4YRtIQVHGLfcPYshefWEOBh81/dsx0dQCxIVNSBNbixV1y5oAcbYf3z6zyQ==,iv:RuAxfhALmzO8Ud5fMgX+YEPqPvdtzLbFwEVULKluevc=,tag:O2NXw2dWilyg5+uvYftzPA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:5TxAEO2LJ+Gk1GbeV8SBa62ImxxAEJq0apW7/S9pLL4axqocAlOJTL+53ofJw5vxjAcc+fEGnq0ePhqGrWUGPw==,iv:Dz5GDRCRLX7IzPhtkyJWr+GOEplk1fitDpns9THIE9U=,tag:k3Agu281zsM8qP+IzsK2pw==,type:str]
    ACCESS_TOKEN_TTL: ENC[AES256_GCM,data:qskn,iv:HpuGSiryxSlFqNMISzopY+1KgrkUZkJebKk1FwjGxoQ=,tag:6SnXmFCoI0wvYJPsofRhbg==,type:str]
    REFRESH_TOKEN_TTL: ENC[AES256_GCM,data:nw7w2Q==,iv:0i6aN47VXGGCC6bs5aCqP/ae+l+uZnxPnYnJ9Q+Kd7g=,tag:H5HNbgUFQtBonWrBi3PW5Q==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:oL0UrkwTTH08nPfImuQ72gZv5qF2JrbUPw==,iv:BCH446rXCIR2jjSO6tNx5abVlKcmwa8kgZGzxcfe+d0=,tag:ijDfzHCpN3dycE+M+krZiQ==,type:str]
    COOKIE_SECURE: ENC[AES256_GCM,data:d+rOMg==,iv:RbPgHRjkaxhxileOQu6UAwMsJxfADlcTeqhk9rU8R9Y=,tag:N57fUgSV/AKeY+cDyGYeZg==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:z5VdEs9F3rEficZha5Powkyy2NrsKHn8PT1Ly3A=,iv:a0lV4hSU9s/pijenTSrX6lub1HwmsG7hgw1mZJgSbS0=,tag:i4CaXCERNM7paardTTBmVQ==,type:str]
    RATE_LIMIT_RPS: ENC[AES256_GCM,data:vg==,iv:ODylQ7TLlJUcPz+PXAU1qslXfXvovFohmMnTu5SPUos=,tag:75sjxV79hClrqYUb54SYqQ==,type:str]
    RATE_LIMIT_BURST: ENC[AES256_GCM,data:Nfs=,iv:B1H53F9LU0vlc7FQnv1zwXP2SQQUJt2SjIMF7lZWvEc=,tag:nDDId7rO4XQYVDPbA2X+cw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:bZNTT+VNiqprnHDX/uZedyoQAsD5ILZfqUbQJ5xO1Q==,iv:QA6azsTEsagkUxbf7Uq4oPEzmKKDE3Sc+hDKsgLUP48=,tag:Nmj96VR7ACSreG3TdRq5jg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:iYyD5w==,iv:swrqmq/h8Xlg/GnFs7z/sC/VsEsCVVWJvd3ec25m8sE=,tag:CB0IQ1vUlae/5S2m5fIxxQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:BIeNUl+K7XE=,iv:iqU3JAex4a/8H/GyqZ5WAPibIiIs4j3/X3BCj9Qbvtk=,tag:oXgBTCCcdZTGq3Ds4djH+Q==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:PQ==,iv:r8ZY4Aw4/sA5SnL6T7BfjbssXQ3becEwOjsb28e4ocU=,tag:tQTaVPGUZPqk4vQoCUvRFA==,type:str]
    SEED_ADMIN_EMAIL: ENC[AES256_GCM,data:a2/dbge7Ff8cMW9cga3GoPMLKXjvhiAteLOhng9ab0fPJw==,iv:OIo7Q9qeBdrDGUi77Ed4hIbftDGOKoT0xG14Q+nbgtY=,tag:hxKxbVNMb0BbBXYdD3j8rw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:NSIKeBBrbPwsfUSRKuMG2nup8nMrUT0=,iv:oD3hgLD54SEj6myMKNAjh3LJfVsGWmyUmcykci/Q1b0=,tag:Jm5o4JAyJ7RXpd8LjfTYZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc2RRdDJKVUNRTVZqVURS
            TVV3MG95ZWN3L24zWnJsb0c3MEJnL0NlZEJ3CktGQ1FqRk1ta0p1Y1RiZi9EaVFN
            ekNvTXJPVWcvNVdxRmt1dUsyeHZmWTAKLS0tIEY3b1JKd0tnUVl5S3ErL0wzQTZj
            UHdMcEJZenV5Zm1iM0o2Z2JjZ1FHNUUKS2Sw88gL0Uu983nSR1F7UDKiegbApgWS
            vvayCMSeAVh7Rne77vY5fenMVXMRmj/72lpBbLE1kAIlv3UhQN05Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T08:05:30Z"
    mac: ENC[AES256_GCM,data:ekb4qma28Cbibq6V9fBfiGMEISr6dbtkWm00mvaAXJBbtlhGhJk4DACowtpuya45gAlWak5nmsvbbwy9EnAbF9Ts4YFVCK19I5YJ/wLR+PnKpV9CwFCvcb0wu5ROFUvEGTfYD2Hp+VlS0HgeTrmpC2iFSP1IX9RuozLnlkCy1yo=,iv:pbdbnBMdNKG5HnXe2YQqDB85xoVIkrWhvR2kuD5X96Y=,tag:MXzLN99TJXrWeEMcfRw0hg==,type:str]
    version: 3.13.1
