apiVersion: v1
kind: Secret
metadata:
    name: auth-proxy-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fPVNca6C8fJJKYp9M3i37+U4+6iJVE0UdGS5atuZbqBSzkzz1qt3FV6Y+P1OIi7VGqrvErRrvMe5Oov90sUgnWCiRGcXvnWnHh/I10t3O2R8KtqL009yMhqD4oIWpU90ZAI11fduuXdvApBW49bSl4k0TiNmAKDpBZEEWsLOXT2HRVKurCg5OKd5+26OlT2zBOz5HyJQrgSTZ/9rpsDYhF8/X2RP9gmZ9BMd3xwqsu4lsD/mH/55fxxWCn+IlYly911t,iv:vfEVe7DXl3W1MM+jJO6WKlqWc32ZfnZg9lA+sVnHe3c=,tag:rwv+TrAN6VdQUplBy3dpOQ==,type:comment]
    PORT: ENC[AES256_GCM,data:LTx73w==,iv:N4+BdktwVo5IkkIzSBLJrApBdioYflP9YSnjSm+XEsQ=,tag:dmQjRfs9wv6Ujr61Ak+XkA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:CGuEr9KSTmZb80AOnqXqwNCFywdahsGulshk7Ypdj/aoLQ==,iv:G6WXSh1H68PWSypVcJWAqjiI883bu2dj+Patl+ESqH8=,tag:Orn5DNGrwZI3F4fUBUyFAw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:vorG/A==,iv:1W6pysjeED1u0InLPznQjmS0S74908bjBzNOLvbJGvc=,tag:8SoafD09EUOIeeHLQ1xU0g==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:j1IQVYZwvA==,iv:rXcV5iPpcoOYkKjznGQ9mVWxS0WHsu1Mhq+3xLQ0oY4=,tag:BefwKZQzPhRSTp3cq2UHKA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:oiLRNK5OgZk=,iv:dFjvRiFZJtwDpE221kyCotfjM81afiYiB7zHgcyzJIo=,tag:flDd+6BxDRP8haW6N0EUBg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:1bSY9qtPkxzb,iv:mFOxNScBLOhXRgUTjUNtUv9Zv+x82oW8URAnBNnoncE=,tag:UdGVLwtuLvYFu2fFuJmd/Q==,type:str]
    DB_SSLMODE: ENC[AES256_GCM,data:/TsBDXFO/w==,iv:XB0nWT5of5HS8MTT4OqVK2/SQ+AT8/0sG7sCOB1f9o8=,tag:UgjBGMpCxZGu8faycBsHSQ==,type:str]
    #ENC[AES256_GCM,data:vKej6LCzy5Ff26cPDRZ4MZ2v/ZwZeT3yarDuIPloqlCd6cj2PEUlthdCCWwWWS0VWwlOUgjQe+8tCRj5pIfwdckWyLR3e8szms6U4pTgZW3lC6YOQoB6nMYgstJeFty1mY+mvm/rPkrU+FDcl6X/0zG5iM5hyRjfEMpV/TepYWzHVuv0Q7/SHllIZPjGjyc0Mwgq1a01gNvx8LdQr1rR0fwLA6oem45VvHpfEERbWs0h1Is=,iv:9Gr3Du3sF45tqM24GqTyrA9Kh7EFbF05pHkTYAN6mNo=,tag:VX0GmZrwYK7InZW5Y1YonA==,type:comment]
    JWT_ACCESS_SECRET: ENC[AES256_GCM,data:QFs96H/c9K8D/qvwUfY40huIF5TdQBlhBCEpgkOhw8NbGJLDfkWfWXdXBMzuykx7MYbXf6Ril/npAAsLPMltTA==,iv:T4m8eWuyUBGIqJCUwNQB+W115sh8MaYFJm3L+81I468=,tag:/kaYD0dO//YZYtJQ09FO1Q==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:yPHHSKGsiSJUwZIB7iJXDw/SVUTle47mbryCdbkiUTKVRQ1v5jsokvMqRutX6FyP8PE74cM+koA2BOWC9TryIw==,iv:neqoQ21xWn9xTogm/QqeiC8M6cezLoPmSLuDIlEwuBU=,tag:9a7+jPzf6b6Mu9GKqRtdgw==,type:str]
    ACCESS_TOKEN_TTL: ENC[AES256_GCM,data:9Z5z,iv:jDGn5/7RABrBaSDpXT5TDa8vfmiWHtWE9+TCmG8OwWw=,tag:lyK9hSBBCMfgd2iTDiaq6w==,type:str]
    REFRESH_TOKEN_TTL: ENC[AES256_GCM,data:g3Nk/Q==,iv:cfVOT2JsSwv8NuUOrDvF/Or+rO8MFIZ7BHYVHyjqK+k=,tag:TVmOtARBL2qCk9hmQT/SuA==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:c81ULvDoaUXYza4OGCUpxGiXftEA54Btog==,iv:vTDFFNsC3Gq3Yg+ZoobrGeAyqRUTRsaGyXLv8fwNqLw=,tag:egfMBV3wcpvrViFbexEFHg==,type:str]
    COOKIE_SECURE: ENC[AES256_GCM,data:ykqWeA==,iv:7ljxcBvRJAhZBwhPwzVBe8k5856eIZtYaAQDn9J9ZKI=,tag:MEhWpugh+/dND6g4/ijY1Q==,type:str]
    AUTH_HOST: ENC[AES256_GCM,data:8/1m6AVuGGCZGzK+atulEqZHXY7asb8TqTHEbX4=,iv:kxA1pvbHE05BmhV5iUwn7XwCa14HHVgsd66nOPD+YAI=,tag:BYj1Lfq6dkHbLZzQa9w4Uw==,type:str]
    RATE_LIMIT_RPS: ENC[AES256_GCM,data:gw==,iv:tpB/NawkH/HrfhoM95Tf2i8Zy/R4A0F3ExpjhGgOad4=,tag:s6UzB1UV+t2AtVicPo6eEg==,type:str]
    RATE_LIMIT_BURST: ENC[AES256_GCM,data:YUI=,iv:0pbuliN5yfRfefKCQkBxFZTPDanOI6TyVD3zs+nKF5A=,tag:t0jDL7c/nsByWOswQSyvvA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:kdc6h1+9EPJ+WE77ZnRp36Yt4V5AbdxLxtSepwLfpQ==,iv:M3Xxg9kC/z3mJdLCdOX9Uw9C+oLnXXcPJ/c/9DhPU28=,tag:jzPIqUlfQyPFiqlq94TgDQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:6lnE4Q==,iv:Ti0U24i/Clrt1fAV4Wvzyz6ftR/H1K8AvHoC9PqwzS0=,tag:rO6aO3CecrdmUe2AAoAgxg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:A7n6Zsec5VI=,iv:bRBpuXXsrH0SoYg3Zj9stn3EyyxSywCq9cc+mmfnTRw=,tag:0ooOeqO9IBGO5PotB9tcUQ==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:Cw==,iv:ZsDtci6WkwvDc9xNZQgkk79kWTYPuWnUc5XLbpZXGUA=,tag:LWSJ6jrjH2K1dYQtU9HT3Q==,type:str]
    SEED_ADMIN_EMAIL: ENC[AES256_GCM,data:ax9yIeB7tmt1BM5gRD4ib6AVbql1qvr4RJ1cLmm9X2k+Dw==,iv:WI4Bk73JjFIhWdcT83cBpjAmU3ZlhNqmY4f3WItS/Qo=,tag:WqGo6J4ljSKhZaSBOjZ80Q==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:6thdPWtyB8LuGominhb4Hh7fGrS/xFg=,iv:dbG3jsOeYjLfY8T0CAVe9aGr7hl6HAz10X3EkuFerqI=,tag:DTgoMD34NMXjCWFCGFYAcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWFNUOEYxekJzM1RmQ2xX
            cW5RL3pITHpyd1RrVHk0NVFZemROelVLdzJJCm95UWpPNzB4UE03bGF5V2hRMzZD
            bko5MG00N0ZDY1ZKVjZZNHZXTXd2QWsKLS0tIGVVVEgxM21ySmxPUmNCQVVVdG84
            a2pQTmxWTEZsMzBVV2JiZ3g3NVYzNW8KwgA1gHx7Bc8GNPLhrTJAVFerRLuDPypm
            gP3PWC79pjumlS75mz4Ew66TCVbtxCrljadWhy5ws+alhKq+DJX3DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T08:39:36Z"
    mac: ENC[AES256_GCM,data:ffxx69MaG/qkChdmL5ji5BixmQqhNzCYvLUpGnEKsqmaou/FcGWsx2jDLbfV0tIIzTKaAD5gKBRcP4Tn8YecV1gf38uRRF6EqM9eeLQFGKwmNsVur6DpBd8lZhaLJzH45EaVnbIwQEZfvk7hHXcf2jsspVgpk22sZ6QAQe0eCBk=,iv:zFVggUgx2eT2II84qGPMO+8jkPjO2t4PRk13vhuhATI=,tag:c9dP0HntwkBKUV3fJVZg8w==,type:str]
    version: 3.13.1
