apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TBwETXCRBWo034Y8,iv:OIePR7C6Z1MQJgXpBRYreOYj5UqxAMxgp1JLkiKp2js=,tag:fWZwUrcphroz5JV/rNfAlQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:g597gQCCe7Tl8FLVVANAN70EjSQQyqf/yEXUKvqIs0o1q52IYbPbULnaKMnZJFRe3eMshKM5uCY71koqAVSAXq1TCeDau2oDNdWzSzboJmdH,iv:/SGSuSx2iUzajbnkFMCokUXWJsO6mRGy05h2e1Rm/wg=,tag:CKdw/8+dWobU9tXomGnyLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscldWZTd2YnZZbjkyZXBm
            MEZSOUpDRGNQTGN4V0ZaZ0QvK2lkOXgvOXc4CnhXeTV6d3JLci9lR0dBZVZJTFZw
            ajJOcm5sU004U2w3Z01DZ3BONHdpUzQKLS0tIEdYbStUSDEwUUZEUHFySHZFWWlv
            MlAreHVZSXFkQ1h6OHZ4MGJ6dEQwclUK4KjyhLcJqMkit5caRS/xJTIOysJNI+lq
            +vR3vhqmuy5yfQKwbf3v53WiMMI2wFZfh7TZLiVrPyANUakOfkEv8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T10:02:40Z"
    mac: ENC[AES256_GCM,data:i0Kx8Q7uUjLVKuumLQMlsdPMS4AUiD2XDzTBV75hMRnbZZCOhTGMW5zV3ygFQyu+2hUVAmLuVTBQhXFmwXAyzwLuvQ/KIbjULFaaV0wk4zZ7hgcVze6S3a7macIfXcsrU+7k532rZHHXqYpSevmPy8blM1FfJTiUTX5YMn7Y7NY=,iv:QdXlBWEjGrDBQIuPOTctY/kOC6YRyvn1X7WTjYO+v/0=,tag:k5WUZHDMveADQiHtqBKCBQ==,type:str]
    version: 3.13.1
