apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: default
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:tYZFhp+tz5A=,iv:67H/rsK3Mn3RXTQgyxvw6nUvH/W9ZBrVJt2E18Y6scc=,tag:kp6cyk3xCnflh1IgozbIhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdVh2MitJVFRvRG1xQjZX
            Qlk3RXIrYldPM3VyWGtELzhoWmN0dktGTUdBCnFYbkJhMFBHVEpFS25TUzdDK2Yr
            RXVzK1ZvNFNyem5YcUd2N21hNzhHWDgKLS0tIGY0YlEwaEl0MGxuSHJBanNPUlMx
            cWJHRWwzaEZVRHQ0a3hkbG83b0R4MTQKcgxmJcKlgsIcC/dSt1ZvtgdvfuTzlINB
            Rc76QZzwPJHJxpiwSgYNv0IKDN3JS8y9xUmW22TYOraQvXFE6EE+5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:05:34Z"
    mac: ENC[AES256_GCM,data:tBBiJ2LlgjPwFaOQGBgCrUrvkeDiUdAQwiBYHh7K+J7nlQLTkCprWokWZ7qrkqaP90Ra6zCtM8qMZvxjA19pzN+HnEbOGLUmffeZNZHJsJwPtIXg5RNMkHjjSUHAFuUvyIgsvjZxAw/LZ3qux5NXs1dKlmEpZM20yUaqqF9PwQc=,iv:4vkrzfWnZUzdScgrSoJqQFB/RMs/yTGbEvXuMifritY=,tag:jeFBI4wffqm/sOshltt6+A==,type:str]
    version: 3.13.1
