apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.24
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_SEEDS
              value: postgres.default.svc.cluster.local
            - name: POSTGRES_DB
              value: temporal
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: temporal-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: temporal-secret
                  key: POSTGRES_PASSWORD
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/config/dynamicconfig/development-sql.yaml
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: dynamic-config
              mountPath: /etc/temporal/config/dynamicconfig
      volumes:
        - name: dynamic-config
          configMap:
            name: temporal-dynamic-config
