apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vmui
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vmui.aashutoshparajuli.com.np`)
      kind: Rule
      services:
        - name: vmsingle-victoria-metrics-single-server
          port: 8428
      middlewares:
        - name: vmui-dashboard-auth
          namespace: kube-system
