apiVersion: v1
kind: Secret
metadata:
    name: temporal-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7Lk0IxtFKqQ=,iv:AjZBMBMOqeIEnEBqChZ8MefMQ0vbmsUOPvQy/8xbheg=,tag:7mw3qp0nyGgD7WC2UdDcyA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:vbNODwe5cw==,iv:ZtKvGBFKR3S5FU6ili4Trw36ZH7n8KyleIv//a1t+zc=,tag:ddfnbGo1tsR8m8N/m6PyPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVmR1VzUwdzg4R1ZkcHMv
            VHl0QUt2YnJtOFVYR0hudHd4aGEySmYwVUNjClRlUFh2TFVFMG5GQ3JpRks4RXZF
            aEwzUzQ5ZWZsejg2SFlkQ2Q1YUpsQ1kKLS0tIEtZMkpWKzJLR0dtVVRIc1MrOENv
            aWxadTFXbmNmWkkyK3YrS1Naai83dHcKA0fBiw4954RIU9nIwA//DHRSnL2cqBjO
            CT+lvvRvUPP0sjtS+P2YJQXowDX3lfCK2r6bFX9Ys4sgLyDi3YT2uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:05:34Z"
    mac: ENC[AES256_GCM,data:QzT/cRULRLhQrlOpaTrW9QQaqLwQ4qmBKSTm6BF6/ZkVJGUUqpREGO1+xGbKgQV3AZ5H/mkX9qDUmZg5QQDHArpYvvX73r/rjQd2pKBvIliQpiHb+H9Q4YVTIeDRgGgKGRiunAdHnQra7DIboWV7anETMYAGOmF1goLtF0Lb930=,iv:6ZaFnUK3D9fku6wVMirJYakSpyJZrAudW6I4KNWgwHk=,tag:TykXvWBsqkdn8b9c+CECSA==,type:str]
    version: 3.13.1
