apiVersion: v1
kind: Secret
metadata:
    name: pgweb-secret
    namespace: default
type: Opaque
stringData:
    PGWEB_DATABASE_URL: ENC[AES256_GCM,data:GpKDT3e0xQbKBTT4dFa5HCq/ySbX/J64Ps12vk/T6J+qxw12tviIgj8Bdh6Uld+ch10T6eSfC7IGvyEXqKi2ststdw==,iv:Gs72b2M+k2SpyDuZDAVVZCNtMLTBu7iYaq68Ieh1Vtk=,tag:qoVFinXDfanmhcuSozNaMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUpLUUE1NkQ3bm96cG9n
            ZWk3WlVhbGY1cGpJRENpSm9UTHg4S3pyRjJzCkp0dkhzVUU0VW5wTGNFenJoZjN3
            OGxBZVlIU09jeDB5d0tHdWw2NzdHS2MKLS0tIDZtbWd2UCtqUDhmYkd5U3EwUzYy
            TzRSRFVGMzJJdUd5c0twK3NIWVNzYUEKdScSNNzZGgtc4G5yaChpDh3T/n9S8pli
            zV5hGrDF24N63o7tPGxby/dRofUW2b23mf8RZEisOudLFaxVUFGf3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:05:34Z"
    mac: ENC[AES256_GCM,data:V4zXQbYfiJHWl0DVb2QZR4TR3xD6aXa1Jm87OWiBJYPAJkfkxQtLJwZHTvH0Oy9g8z1jvsf0rQWbqdq1DGSN1vq1m1Bc6vR4RlYioxZFkQLzdZMbs1hh0k8SgETPOSZL25v/7m9NDLQdGut7idtrlyp8t7KdH4EdpHjepcww8TM=,iv:+IEbmJ2VlHu4Q2YvZgBP6xVC28quR67YsL4jjfvfmro=,tag:aXOZR0BGopIh+98FP2flSA==,type:str]
    version: 3.13.1
