apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: default
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:QgdkVi4QuBPoiFjG,iv:HeHAxHRoejwjOP1THx1w5uIGAk2HIemGKxTu/SFpfjU=,tag:kG59Kt4jElqNQgVgQRSA7w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:eY4LH0rHftgsStA8yxz8MqxIQv4V1/gNmTo19/0PQU4kJPYFbucQbIuf0omjMzl8dQUztDOfEVG89+tmw9ju9fQoCi+LL22uF5reX2kzilpd,iv:akiQrEAyHLwZFdNqx1NFs6Wcj2l/kn3XJXe9GasNyk4=,tag:cEniB5t/kUZrnObdoGNwBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHo0UDN0RUJYMUljMkFK
            TkV5MHQ3UkkxNUgyd1piNFpmV0F6M2crakNNCm5IUGR5eldwYlNIbGNIbDhrS05T
            Wm8yN29tZ25qYmJQVExIWnVueVJIVjgKLS0tIEFiZUtTK1JtbzFzcXp3VVpBbGo0
            T0c1aGlRY2JEdnllaXBjaTI5UDlqYlUKSAy7WPkk8URuZGiGTaZa8lG6vH2JgxOg
            xtigbPtYSLRTx5PFZRMC0dOi1xktpq7VcMsGv7UKNQD6Xaq/JIzTxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:18:29Z"
    mac: ENC[AES256_GCM,data:Yt2kjvi04j4NC74X/szBi0d0VZskItCxcOKbKvia5Aw+mERMa/dblRACAYOeVRfKN9sG/6+FkfN7Ja0ZEcXLaFr5k1qGWOViVcSx9MN+MUXWdNhE244RxScxpoPar0d1JnplkJnojBo/4QukFtre+Zwlep5Ydhc1v7B+ZxICAR8=,iv:431OOnoHIB+2yQXLz7R64DCpArUqVeCP7m9di/N7gGM=,tag:kpST9Kre1xeSWFO+s4mq5A==,type:str]
    version: 3.13.1
