apiVersion: v1
kind: Secret
metadata:
    name: money-order-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gxJnvd65gXXJ/GtbOGoURFUltpV77sJMeu5kArOdaw==,iv:yUxX/zW6VH+BZThWnX/yJHs0f66TN4NZHZJ+yFWmzsg=,tag:90uq38sHE0GAnw/iRRN4Mg==,type:comment]
    NODE_ENV: ENC[AES256_GCM,data:P5MRUkpXeugQwf8=,iv:A1iRqocf2Zqg8hB4GDbnHNADAYWrxAwtlYT1+FS+SEc=,tag:UQK4JP52LycpSK4OWtvrFg==,type:str]
    PORT: ENC[AES256_GCM,data:dmwjEw==,iv:6cBDulHqrC0+FMGVGqi73031g5ZKfpzqqiwhCWcBEsU=,tag:vkCplM1uicaON+oiJDoDTg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:Y0QTUSALcG4HGv8F1cdi30IKALYqHIxa/wromXCgy/2Dlw==,iv:glaOukmhstmYcDaDKzBiWirE2S7CAcUImV3MhT/RHkg=,tag:aG1YCqKTKRd8qviYcUr5CQ==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:Dg65rQ==,iv:iTOi8wa+687qqMBqz9f66BIE3OUpCBLN/f/CmzOfMYw=,tag:QqrpUUpRJ6KI3qGKT0aHJw==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:IKYtcBmjrg==,iv:7Ox+M1VE0Jo2Rt03D/VVP7LYMZGi3JhvK64v4+t4Zvw=,tag:aPz0beTofIkZnxyzrP6wYg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:jFw1ognYGFU=,iv:pqDZgA5RWGczNLZ8dzBfBajcWUrHeIXPV2f7Z9+Kj9Y=,tag:lfHa56W4kPoeEE95/efSSQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:eQDlyNV38Bh9G2A=,iv:3nL+8f+UkgNA8M/VRc6x+WijGELYwv3byVTnQ9HIt/E=,tag:13lqPp5PBNxKNUXuBd0HKA==,type:str]
    JWT_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:l53kmSCvOtJPm2CgAjilbSNyvdtYZOrCekVT8nzh3q7GXb/Grqd2wK6MbzXwDbgbIVDh6eNeUOgRGHsAQl5YNw==,iv:GfCnA2NS8sNqksU1kVd7ppQAv82jIAP6TntrU3rQ1MU=,tag:WrL4RtcGoFq329Uj9qeisA==,type:str]
    JWT_REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:buQAu5jHePat9g9AMQJHI6Px1NYxjB2wYSDCK/wEmsTuYsadxGAm63526vYokLaxZHeyYNVd6OZy5z2k+aNr/g==,iv:+gE77OrjC2zRyE8lYG5ZH8BpzC7o6AjlNTaZVSvGGGY=,tag:cY2vEkVFGT6CHI8V5xVfmQ==,type:str]
    JWT_ACCESS_TOKEN_EXPIRATION: ENC[AES256_GCM,data:iTSN,iv:MgX7l9jzPPs0rgtwEgMdCUAldZ2Fe/RKsmJuNP+sEFw=,tag:KvP93UpT4cXSetXW34fEuw==,type:str]
    JWT_REFRESH_TOKEN_EXPIRATION: ENC[AES256_GCM,data:SHSMZLtW,iv:FcRiO9odxxychJKZD9XAajQAAOR0vJJ5ItKw5XEGTvM=,tag:hTKvyWKZTckLSmNqJzOQIw==,type:str]
    API_KEY: ENC[AES256_GCM,data:YWFT+OhtjCkuTfu6piA=,iv:qYIAl34rbbLU3gDd5WvE6oCPBYAZboNwElVNffIDeps=,tag:7bNri51QMxLGmu5H3ReBQw==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:UGWAkeSPi0cR1wn5jsJxzpoSxzkE2Lv7zx4NHLQFvcgqG8k/d0/AuUVKwlyI+E8=,iv:zBzWoo5KnB+SgNNFXkyQYbivNugpDHURnIfTorlOSaw=,tag:cjNYPyZF52eAihup2pq/0A==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:V4r9AM9GJ4z5+tFZ9IBPdMumRT7v9sCQ9n7E8Nrc+g==,iv:qkUvW2TjMrTTbiowqOuPpO/TfzYE1g/IGG2xUeMBF80=,tag:7YYfG2HAKS9/7Xzh7AH7fA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:Sg2etA==,iv:hlBBqsk05Kqv7vRiK5CEdYqNzEivi/NUZK9YhDr+2bk=,tag:b3fOvMKFlniVnYr5v2c8kQ==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:AxbuQiqj4Q==,iv:FSChySUO0+Vo9cUzLLA8fTqbJLtmsp4R3ReoTAkAo/o=,tag:Uv/AvnjQ3WFcFrghuxengw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:a/NauBL41CM=,iv:5gS2MhzFQCuc7u0IbBHqlul71DgDsFeYt0pC4hEEokM=,tag:gtqJLARRhwNH6UNIMDVM3g==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:Ew==,iv:FA3/MRgnXx9d7onVHR9BYFkdE8GRzuowF4wPpsaFBAw=,tag:3Q0TAZvTy9MODTVPMGdIfg==,type:str]
    TEMPORAL_ADDRESS: ENC[AES256_GCM,data:JHSmHHuqJCi+/Zn4wtKN3L1zTBT49PsWfn77BFEAsLTDcHXUdWVt,iv:EYfLkOuCqxa0/lMwvINqptsSMreGR/cE0AlSEMWj0cE=,tag:BFNDHpdpW8wKXJo1H2mxBw==,type:str]
    TEMPORAL_NAMESPACE: ENC[AES256_GCM,data:QajJ2dOZZ8hk/vA=,iv:0z3sp0INZhgCPk7gM2FMZ9UElmeB4IKHZZolyOD4wDA=,tag:xYqXhIeia7CKxuNp01MIbQ==,type:str]
    TEMPORAL_TASK_QUEUE: ENC[AES256_GCM,data:4H+QiFzBgdmB65BdH8dDU/BLbdYkcA==,iv:R4YOcwepcbMzxeY+LSu9nRhh7PDtWR3spwT7O8HSXIo=,tag:PQmYdk9U3d1/xof4zhj2RA==,type:str]
    #ENC[AES256_GCM,data:4wpDMow8EUcBjeBc5urbk8xxLLLp,iv:jdjnnxUc+341xBipVgumpM979J//j5AWNb5SPswum/s=,tag:6fglB8ZG/ApW0uKprZ+Lug==,type:comment]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:pkwaxKL6YsOXw+jJbek=,iv:+mht8ANpfmApk53e3OpFo+QYMt4RVzU/8XLHmgHrpl8=,tag:ZBVNyYHTpMQXRPAtJW60XA==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:6pOWmTy6nLSfsnzu8w==,iv:n/85WNhEbjPjktMnKWyJcW8738VPPyH57b8ZnBEtsmo=,tag:hSNgaFrauh9zlq1OStDASQ==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:+Pt1SxpF8QqQOsM9,iv:MuA35tkZlKO2nxBJ6u4X+msPUzu0XfJNXjJVEoWHdnw=,tag:EPOJ9MMys4ezzKE7lJZ3cA==,type:str]
    #ENC[AES256_GCM,data:9Rx/omyYFFo4w2I=,iv:TyZnrlEZqAs7qEZiXSIcQGmjsN5zn1RsxRbgCsrr+rg=,tag:ky6OmwBELLvamC0NxA6WRw==,type:comment]
    HEALTH_CHECK_WHITELIST_IPS: ENC[AES256_GCM,data:nRcY95GQMEkIKEJoDw==,iv:oQhkj/nnyZq2UAJQmnp6t0FyErms+bbhI0LlWUn06RA=,tag:mckNawaHb+P5fctkx2trXg==,type:str]
    IP_INFO_API_KEY: ENC[AES256_GCM,data:s6FLu37ke5GJAuX/yzU=,iv:4cHW0UyfgMPAHDkT7R6AiTX+6UklVp2/kqDnoibgwLo=,tag:637zYi3jk4Y1lL7Vhn835g==,type:str]
    #ENC[AES256_GCM,data:Q7Szr7z/oDlt4Q==,iv:RoBFybpuOTEoB3PCjqPjwWXX/Jg6jUTtAPF9R419XP8=,tag:/y8bxTDUQy5tDY5iIhakkQ==,type:comment]
    WALLET_DEV_TOPUP_SIGNING_SECRET: ENC[AES256_GCM,data:jK+irksWaXU8JANm1yOll+Ya8MTORCpF,iv:WwjUwnrPoflTX4AR/twk6PH3zwp/lZukS3qaaLifWsI=,tag:Ju/YXzMWJ4nmL46caMhYBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTnN2NXp4V2h1d0ExdFRQ
            Wk5KT29pR3BtdEF0N084bWVvTWFKZVVWUWg0CmRGM3hudXl3OXpiT1BrZUovTHV4
            b1hsZmhrM1dzOHFvQ2w3RFd4ZndHV2MKLS0tIE5YVG1yc0RmM3UrRjIwS3RCSmlW
            YVFDZExpcWN1eEU2eHE1akZrVkZUMWcKCpX4JlyrFKEN46sNS2G18jTeH5I/Ynek
            4DbtyIBBZtbVv0wl4qfkrl1olhyeJBGxKHT2Q/CR5//ItXA9FxQo2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T14:39:21Z"
    mac: ENC[AES256_GCM,data:HGozY2psaAITangztj8mU3TUqdNo6IM87HkOO2PvSBgUsxF3ED9JXTX8OUGBKnCtyTmG8FolzUTHRAk+PBhDHv9/lTs/2/AeyGV8jeQYbp7EGJ59ufsJz3bNfC6zr1jpvVmIdeC0azKI4s5BhQTZHbTQJD81vLX/TdvOhxOg+bk=,iv:wOJrxH1VWuvtb9TFFJGWEXFB2PDfMH7gvvTkIHAUijg=,tag:vS6fd72YCIGQ51wK9JCXSg==,type:str]
    version: 3.13.1
