apiVersion: v1
kind: Secret
metadata:
    name: money-order-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7qHLWF4eIxQ/vWrnMwimn3i+7QPu7sdaz/lWh2k9Qg==,iv:96DZqoteI/lMsFnnxsESWE4IXFH+SDoRPO+eeir3qAU=,tag:ek1msRE52GdPXBFAQTvEYA==,type:comment]
    NODE_ENV: ENC[AES256_GCM,data:rEvC3UU1ujZCtHM=,iv:U04VUZIMRGA7JSFza31ARwrX6EnzESj4CegoP+Qc/j4=,tag:g0FSuxNhkaDd3OKPeV4k/w==,type:str]
    PORT: ENC[AES256_GCM,data:6GqWbA==,iv:R7dgk+X8+oQy3wGVz2vOJGFUdGIoP0HWVNMGw5AgnYM=,tag:+gF6ActF9kg0+cbo3O9G9g==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:6c8dCJI+xdYWG3j2Zw99kNaOqYRi9YHdo/ecUfYAMtOn5w==,iv:370qN2zGHuIx7k3BgnBsS6PiLvztCuwuIDR6Q9OWS3Q=,tag:PD//ILIF6B0G7LLijAWbvg==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:FVi9Jg==,iv:ifeQmco0895gqwKZBOoxknTc0vMzHDmJIEwr2L72B18=,tag:jRDJ7LTfkUbF7/DoGhjyTw==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:H91I/opz4g==,iv:D/5sEfOgF/Tbvs/yFz/syYbMIcDU30qoo0qlrrYd5ks=,tag:UAq17FIvMPBobu1MpLD2Xg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:0+MQGHrAiHo=,iv:8ZDMxyYTuui8AfItnLDgr6hnqULB3u9r2TcjZ896oC8=,tag:WaLtJLT4k8dPiEDO66F5Pg==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:xO2xmMO10LT0az4=,iv:puQqAyksY7Jt5qFxi/GxYkRkTgbRwipATJc+ktPJJtE=,tag:31UizcNP53mdPDy396iEVA==,type:str]
    JWT_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:NvcJ4h5N0E5qdRGYFm0Y0vtNoBvJFlFSDw6hR5vcEy1BNeECr7wYjHc6AMOI7OqJ+jLCA0cqW9cwSehXN7WagQ==,iv:bT492X82IjudfuTL3AnjNyJ5e4Eayoj3Twl+vTJql/g=,tag:xB1CedfQeuuyOYWZpO2/Hg==,type:str]
    JWT_REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:915FHYnieNm3Z+T22ww2s0x19rP3g1yG6HCp1oNCIL8+K5F9kcBj6vVSRikeX9NYr+dPlSkESZotqV0DY+wllw==,iv:CPkINg3ZRQ6tbiCShwGdoT+pxY95ZTke35WPCAnEAs0=,tag:2QUsZK7l4TzdEQuUANZpaA==,type:str]
    JWT_ACCESS_TOKEN_EXPIRATION: ENC[AES256_GCM,data:pZow,iv:fdZgINKHyaCX4NlVQ2LReDeqMBh3Qn63o43b11BE8M8=,tag:vVOEeriDQp7XD6+aBrh8+w==,type:str]
    JWT_REFRESH_TOKEN_EXPIRATION: ENC[AES256_GCM,data:DBBeu4j/,iv:8hsuanWny1+fdIH+ZIPWKAKOsTEeABneE8dUY1fnezo=,tag:8JIU7Mq0GhxbFBsymBBvlw==,type:str]
    API_KEY: ENC[AES256_GCM,data:o0uLmUGrElSO6OmdtvQ=,iv:H+rWXzJiHype9a7O2e3FN4DTusFoY1vmyW8S9N0X9YY=,tag:3a41rXzXfGmS/VaKcHJgtw==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:t+jFIzgjFZ7fpQOsuWt4YP+5iISZ9q8tvoGEGIILNA7VerWhuUpoGjmCcisSPm8=,iv:NptVabQpNSxtp6XOFccp11GqNFADBA70XiSMHBrMwO0=,tag:VB5nTE3apjk93vN+dY/fVg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:OCA6rn2HivNGWSKB7jDqFT5S88isP4v3HrCTnVwr4A==,iv:oN91M4MUemK8mMxIdeG0zVRZFORJ2Qphwp9wCYJ7BG4=,tag:ziF2jwhwHLubrXBbDodmbw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:nc+mOw==,iv:UxQyYsaGhVPIVyh1HWoID2tlC82rxf8Nb3nMZO71wBs=,tag:D6CvHxtJYgtvRrt1WX4KRg==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:wJZ1m3vGrQ==,iv:x/XUbk0ETtTzn1Soe5gEIEYdHPWNnRlGAqAqY+Wajmc=,tag:rdnEtbQI2KTXOIQ7daGpoA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:FmE+7qUskbc=,iv:e8gS9/BqCUiwzghNLZK8tqVTioLQfKgeZBZ6CQQEm8Y=,tag:J8r4ldjrxYbKRrZbhzUCXA==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:Kg==,iv:0gbgJORPfNFEkGAie83Sk318ZeVLuzT/BG9eAVsTYSY=,tag:D15VlXW45h28KWAyyxC6Lg==,type:str]
    TEMPORAL_ADDRESS: ENC[AES256_GCM,data:gaTQ2zoq/wPDCpppL6Bhg1U+SzuMC4IpqkjsX+f3P109+YUvnNPQ,iv:TI+tbfFFVSo1l53FZt0Xu8qbll2xCIx5NUhMkXbc/Xs=,tag:a+lVnevmpDJipg0WT5vjDQ==,type:str]
    TEMPORAL_NAMESPACE: ENC[AES256_GCM,data:uIBdqJqVot2TOc0=,iv:YFb3zn3BiGn9vpgC70x3gyal3j53Sgy2pc21cQHjwlw=,tag:ZfDgSrwAdu5oMijKTMFqWQ==,type:str]
    TEMPORAL_TASK_QUEUE: ENC[AES256_GCM,data:u4gHBXuOcQRRlVhKYrMH2edjQVhGIg==,iv:4a9lpEzKys4R4Ru3LFlsXbKz87qXLWG6N+TPvX+U4po=,tag:C1h8+zh2H7qeSs+RIyWtDQ==,type:str]
    #ENC[AES256_GCM,data:CGT4MXS5PvlsaPn8ITKbhANSBTmI,iv:DLpMfT2M64TkPhPeAmZNc6nQUoI221/tSziPl8mr0/g=,tag:s//eJOIb3f84eQ7EkwoLdQ==,type:comment]
    STRIPE_PUBLIS;HABLE_KEY: ENC[AES256_GCM,data:TFvLIc02exV6a2Zdl6s=,iv:54ty6WefL+7O7DhTI4YjUsWIGj5nMQ/0Mgq+7iwQDEc=,tag:pzs77C/bD2stcavUVJAlIg==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:HfZ8d56eh7a4ycR48TA=,iv:PSAUZ4rr4LWu8m/PENpFqa0ngk/l2LLi/QaZD1vwnWg=,tag:xrqhVGy9L8CS9ag5Vp92yw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:0i+/IyDeDzk7Kmtk,iv:zuCAmo7bsuzlgF6aTtLZEpvJUckNDtIdWKzyDMQnvzs=,tag:Gj+BDOP/KNNxF2sfgbWWOw==,type:str]
    #ENC[AES256_GCM,data:WU1hzox6RAtqYWQj,iv:qFN7jx43YYOsdXMveiJZzwhl/2S3vw66Tz3HEw5u7i4=,tag:VtvSbTbhWoAtWJYK/vIlTQ==,type:comment]
    HEALTH_CHECK_WHITELIST_IPS: ENC[AES256_GCM,data:xN/VSN4U75Cekgo0xg==,iv:QAzf9EZR3F5d9myv0P6jBWYJ7MPr7Ts3HIV/0Bdxu/8=,tag:5Ispoktyzil8T58bRoVONg==,type:str]
    IP_INFO_API_KEY: ENC[AES256_GCM,data:ZKqC7bF3h8sMYoA3cbE=,iv:ECA6xUBKQCO+6FFjk+Efmko1+mTYDY7ACfTC9LATMxk=,tag:fDIFIzqkXaXPGCqFZn30wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldWpjREE2NEpNazkyYmpB
            ZGNGREJjQkltS0RmOVprQzFMSTdFREpQcEFJCmVudERQOWZvYmt0SlptV3ArMTBn
            dlgraC84cHlnQms2OWIzbnpSUWNlbG8KLS0tIG1sSW9qQTVwcVByUmpBUlllTDNP
            VSt2ZW1VRzNldTUzMGUxT2h4VGZzalEK9bocV61PlDwQbeI/g39Xki0b2Ygfn274
            /ilrQMLrP+/w5WSC44scKD7K0OnAjAz9Xeqik2MvGQcDgDahvq+mUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T08:10:56Z"
    mac: ENC[AES256_GCM,data:fvIn8NiF0NlO6IqpSphMn0Mn73TBpioB2olMfGUTUzoVAJBiLvSwEW+3+wc88mhLVV/DxEFrm6ixvoleHLzN2I5y8e/VTKqENH/uQI8IVEt1+R/8ownv4TOER1xprq0HquuVSOY75euYyDWtV59prOQEZ2aa7PuT247xXCQiisU=,iv:tKHwisjD5UpkLyzRR+EtTih/l5QhM5TzWC36fM3O31g=,tag:/luu0QF5Xf4O8bZg39123Q==,type:str]
    version: 3.13.1
