apiVersion: v1
kind: Secret
metadata:
    name: money-order-secret
    namespace: money-order
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MJoNDp5eVGSsFk15fCsoFeMfsD5tR/gTos5OLdtw6Q==,iv:SEvgEo1cVS9ibJHYA0TxhvA4XA48fd5EDG4c70wzo7c=,tag:tdsYml7G4tXbsvc5OgZM/g==,type:comment]
    NODE_ENV: ENC[AES256_GCM,data:2fEaLZ6ZBONFO0U=,iv:tXblndbmdyt/DTLWl+spGWNnUZxDrudkiLjzOD9rNaQ=,tag:N1x3Uvy/s5JIDsYCWDaAeg==,type:str]
    PORT: ENC[AES256_GCM,data:ti0lvA==,iv:9JIki2bZh/h0NyXIBtzy0VWTM0rbuEfnOXWb0hdV+YM=,tag:bNVeEomjgxeNP1KjoxsTaA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:ynnV9IhoSP7Bp4m69k+pDv71zO/sPF4xeLxshEiL7sGKTQ==,iv:nW2bgxgBNcPdvFbBSzc9CHhur+9wIdtdgsY3aSJN1JE=,tag:rYosbk3pYTf4pbZOlTKl6Q==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:JuRTjQ==,iv:Al5JvRS+EY4kgoXtvZhbm46DJAh/Ix6vcHrQi/H0fck=,tag:wL3vbflC9mkuq5MNFrx5FA==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:nCLRuwbBMA==,iv:ku2q+mPVrQShlzi20rldXbSCMNWx9qYfPLOsfLleNOg=,tag:g2sbFnTzWb6DKf1BXi6CaQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:xDSx4l3Sok4=,iv:jXTSRgn0Urcw5eYWGa5cEvpX90/wec31K8pHfB6qXgY=,tag:7VzdxFCXiwJiriavJOlOrw==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:XIKl58FSZn4hDh4=,iv:oSY21dX7eCF/RIGgZfuuPkf5YZAxwuXY9bZBrKOMyo8=,tag:6p6JV7/q895KNYnD80C+tQ==,type:str]
    JWT_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:pCntOEyVdpw2sWmQ3uayBqyjUkOVz4QUCIiFkLINUIRnSHrrSxz1e/yaZTk9JOruXZy6WiPEIoSqbp4pec5QeA==,iv:lPXVxC0kYHND9ZvQjMoa1ahlZ3QF+W4ROR0t9lZFj2g=,tag:dlhq4tcm5+yg73lz6RiRzA==,type:str]
    JWT_REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:o/0/ck950bb4siB9MUcfTbnrKSbEpkMJDlj5Q0/5ktGwsnEtaeW1Am21yjdM1NxWsuaUhkdSHHJIldtbOreURA==,iv:OupwmCaDCNK6YNUt1z29ASJOvhNAS2mJjG3OezeAt/4=,tag:1KradD05Sp7JnmC6E3jHVA==,type:str]
    JWT_ACCESS_TOKEN_EXPIRATION: ENC[AES256_GCM,data:QVm/,iv:4JhYdyM76RbaEBPGMBGFXdywAcTwu8uAAKSBG18+zCs=,tag:fNVXipRX/rs4TyywEUiKNQ==,type:str]
    JWT_REFRESH_TOKEN_EXPIRATION: ENC[AES256_GCM,data:DdPHuC/O,iv:A1x3MzmJL1rnwOH7wYTy85/swGmMiT1gdlXJOKBLfAA=,tag:Pb517L8fOUOpJR2QeHP50A==,type:str]
    API_KEY: ENC[AES256_GCM,data:k4uMY06gXQMsUgTkiqE=,iv:EDHa/WHOIJ9LnkJHncDH/6Ir7LLj+baTxr5g8u8javo=,tag:3T20WGKEkzhKQyu74kosEQ==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:HrEwkcteYaYPoAvdm6fKD+kkZ0JANp96PEg11Igc3MGi5qKxqsh1WX1ZiBKCxO4=,iv:V78Uh9W8FlKBY4OgLQBoW+/gG7cfBvCaf4Rpn/E0Svg=,tag:eddhfcNu+HrYkaH0Rzd3ew==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:pjfe73IVL34SqAUt5gw4xqReICOfutQTl2vIRMm7Wg==,iv:PXC7vYJvN+wyDHBEZyYDtyLYxeluwb/Mj1ZFO8ZxS6I=,tag:iztXVNbaw4ZpRaH24tBFpg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:Fu1O5g==,iv:unh8i+OSpfR045SDIuEd5YsV9r93FsTsB5yvLfdxOEA=,tag:i26eVztshifrPNfeMgZh3g==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:8kpqyrk6Kw==,iv:eaRW/AYnekrhnXcsy4Gn7Q4wB1VugoCRVZkZfbmlKrM=,tag:vP7qgQSgVhJmPpb5+4tSRQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:Tw0I2qSwG9w=,iv:+0BJRCVuxOivCWDRYR5TP7wQx77qK0B+czxxpmzwhJk=,tag:G88MaPSdoqAEgMpdnD7BLw==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:3g==,iv:MNZsQvOkgkBL+gKL4mZXRc9yIFY6h3tVcdxS8mX/Qzg=,tag:342H2tKsEOQ4LFDU69+jXw==,type:str]
    TEMPORAL_ADDRESS: ENC[AES256_GCM,data:CQzgHyFBMpa1NJSX4cQciXHdN8/u5cUFnngMPJR8O4f95yt6xnQm,iv:R78o+atX1F4Ri3cb6Indm9+EOWoggfMPIHdp7MDJUGc=,tag:C9p8RZg+T0SnhXoF3nMFWw==,type:str]
    TEMPORAL_NAMESPACE: ENC[AES256_GCM,data:oDQJ39I9csjgR+U=,iv:36vl+FDepMBLq5/fqbvEzegzseogz6aGOaONuZ2oEqE=,tag:Dwt1iOjoawXujGVLjMmi0g==,type:str]
    TEMPORAL_TASK_QUEUE: ENC[AES256_GCM,data:vM1vPtCJyIU1KkRsLA0th14Nn1Hqtg==,iv:lvpKyv/kh9jOPi65oSZ6anlPAPYyj0OABGli4NuaWIw=,tag:MosLjVufMSereKZNOa/VJg==,type:str]
    #ENC[AES256_GCM,data:xgeyKt/Yhhv1EZ8CmW8vyqUma0Qx,iv:aEv+w58F2F15FkEbZtuGWLl/MFj3wAGpZSPjSN6hsyc=,tag:slK4NicgkiMjs7fSETNtkA==,type:comment]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:UV+C62NuwJ2CZCkFKD8=,iv:9ij9McblY70cI27u471n56+HMhIMJTfyXNedojNn4nc=,tag:w7JvIvDFL+E+AfiVkvGiZQ==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:NEbGiZjhL1V7GKEBSg==,iv:Gl3naS9jbpNRxB2H2M9wugERgeSMpJIT2IXqzaFb/Ok=,tag:hhskZVptCkrL+Zi+hmcgpg==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:8oJA6/XMLfRpx4/V,iv:Z+lK8pWVBodgb+in1jZkkysoGU8hDDkaKIrGSEBOzYw=,tag:ZQWzJw0IiPqjOR/+J3v/6w==,type:str]
    #ENC[AES256_GCM,data:UNV5FYEZcRCmdqE=,iv:aRvDg83ELOPqT5rxi7aV1pRWJUW4lqrR8/USfSEjv6s=,tag:QfeUY2PPOB6NeP9IrgvFRw==,type:comment]
    HEALTH_CHECK_WHITELIST_IPS: ENC[AES256_GCM,data:bFKbgz4zhTzezTbv7A==,iv:J1SWkDCz1by9H9AwOgF2vIowxIlf0I3/1yfbE1q+uf0=,tag:+ZsQfBJ/4WZj02716C/6nw==,type:str]
    IP_INFO_API_KEY: ENC[AES256_GCM,data:vEt1kfCAXoXLg3oMeHs=,iv:d0Qdlxq/rEKvZ/8wrIktMwx8XKspv/TOM11pAE56EKE=,tag:BwdskM7vpp7vM/YYTjFtKg==,type:str]
    #ENC[AES256_GCM,data:WZ3GNoK0d3WJng==,iv:QiLoEt99G8PW0rAn5qOzK8ZPgGq2gZgUoR1435YE8ec=,tag:h7BkvzzT2PvYp3snNE3ewA==,type:comment]
    WALLET_DEV_TOPUP_SIGNING_SECRET: ENC[AES256_GCM,data:mxz2JtNQj8TSh6mgH/cCxqpz/ivkz2cZ,iv:PKSWlvH8mRfORwBonyFSmWg2oHjAkqhPDYbNHzOu15E=,tag:S+LjDW25OotTsZ7a0k863Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S1RiWEFubEZ4TmxtRVhC
            eHlQeUl6bkx2QWFRa25KTXV5TVIrZDRkUkdJCnNhaVRYUmFnZXIrK3M5cFg2Yzdi
            eW52eHpPR2c4bFNtNzRrOWVwQ1QvdWcKLS0tIGNsYlRtQ3pwNFg4TGFOdkhQc2ly
            emJVZ2YyM1VLU1JZMW40RTE5VUdiUmsK7dv1GrdPtCyY0WEC4SPE65DowTmHJLBk
            IDlpa+sFSPKCY1qMnoAw2q6Mf0PGTrgD1RBYshFODx1egK7olFJ8vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T07:54:02Z"
    mac: ENC[AES256_GCM,data:Ri0mUfD2i6Dj/4BO8TJfJQ3vK4VEQZvmazWuIj0OYxm4rle7hAYH4xUX4ufVglJP82v9SUBMCfFwKuMUxDYhny3ENlZ+QAblNbZWeBHxqgiFnd6zYSP9TWeofOv+tjFJ4fhCtv+pMzY7Waf6QQ1GnWId7Ry7ADuCy4ISHPi/VjI=,iv:mm6s22WfbZQqusAzDikKCfijyoTpqTmXa6Mlda8n1Y0=,tag:DnCrLhim4QFahppwTbU3AQ==,type:str]
    version: 3.13.1
