apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.aashutoshparajuli.com.np/pgvector-pgbackrest:pg18
          imagePullSecrets:
            - name: zot-pull-secret
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: POSTGRESQL_ARCHIVE_MODE
              value: "on"
            - name: POSTGRESQL_ARCHIVE_COMMAND
              value: pgbackrest --stanza=postgres archive-push %p
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql
            - name: pgbackrest-config
              mountPath: /etc/pgbackrest/pgbackrest.conf
              subPath: pgbackrest.conf
        - name: pgbackrest
          image: registry.aashutoshparajuli.com.np/pgvector-pgbackrest:pg18
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          envFrom:
            - secretRef:
                name: postgres-backup-secret
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql
            - name: pgbackrest-config
              mountPath: /etc/pgbackrest/pgbackrest.conf
              subPath: pgbackrest.conf
      imagePullSecrets:
        - name: zot-pull-secret
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: pgbackrest-config
          configMap:
            name: pgbackrest-config