apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:rHqDcZp29Owr,iv:EbjfjytdF5SX0VFbCYJIH8qHYFRdQSS50MS/j0xLRwM=,tag:BkgKfzBtS4lbe0TmrotRLg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:r1uIPbvTfXA=,iv:jE2t8oYlJxi4WoGnzHfq1vQW//wHG/mJ8KEKKANbErw=,tag:/ThtVWL8PDChh7fsBNqDsQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:7njEO6V6oQ==,iv:rJjy6h9VVdE1de5+SAH6C7GzEF25Oe5ApkXyMoUEDQw=,tag:Ha1Fz2nyuesb4iVvgZYeGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWTFJdGZzVjZRSEhld3l4
            cUIrL3JtT1M0ZTgvYi8vdTBmVWlwR0EyREVBCmVHZ1V1UUo2cjNBblBBNURzZDBV
            aDczbEtNWkFETzlRWjNKd0libkh6UWMKLS0tIDJUUXNnRGY4Ymw0emFVRUg0MEhN
            amVSanRXRjhDWUZzcjJzdUU4WFJVajQK2fIozXqotdwRjK/Vukhq86Iq/XQJEdhA
            3RWl1ury/1gxYF80jy0ULzi8RZZuDiRgx3uzXnAiQRuSVas+xedLJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:05:34Z"
    mac: ENC[AES256_GCM,data:Avjis7Xt1IY8GTWzeapAqeElxrz7o9KQGd7aQbxPOQMEzimeeHaqum5DNFah3i8rZT3YI9zAcf+VgXkKf62BnYGV526xbbzgIz2GlYbHuTig8iHanqAiFlgABtU5GD1aSIWT47lJyf4i4bEZWLb5tWEb2A2nBFGk0VxS4fBOMxA=,iv:VL1Q8n/brImck5ZoVyH5TVCuthXSCjpBp+DxTHTehFk=,tag:194E36QhjfPWXM25mY6U+A==,type:str]
    version: 3.13.1
