apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: temporal-ui-auth
  namespace: default
spec:
  forwardAuth:
    address: http://auth-proxy.default.svc.cluster.local/api/authz/check
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Auth-Email
      - X-Auth-Role
