apiVersion: v1
kind: Secret
metadata:
    name: temporal-ui-auth
    namespace: default
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:oV3zrPTszKEfCGvYFEMqkzrB7z4Z+1xKunJnehCiSEsDFAF5kM94xoZs+ifMpFDozag+u+NVEyp3spJHCDZPQFXu0Q==,iv:JuyXSPnEE2toUVV1C0JxDlXpw47hXANOtioRmH4UTc8=,tag:IY4NAfzl5DbbsZITks0xNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMGFBdDk3Vk4zaDhETVJn
            VHg1eWl6Tk9KRnZkRTcrRTY2VUlVc1RCQjNFCmxzQXRzRnhxY3MyUE01TVFMT1g1
            VW1iUUdTU2YyM0pKNXppR2JTWjAzRTgKLS0tIGJEKzE5c3ZyemJ2c3RsbDZGelhE
            aUhWQ1Rlay9mWmtINUwzeGl1UnkwYUEKU3+1AJd2ssGsgdSLzxywlY2oiMRzpCDT
            x+lJd0CX/vZWW4pTitQHCE05eGPVEgv0Rc72CG2C7DTCL9q3SZB5LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T13:10:32Z"
    mac: ENC[AES256_GCM,data:MDSwWWoIX+L96yisJl/0m/ITFKERGk0o1zRvGEDpHzXe7STWn6zT7A1nzyj9kT1m5G5Nh0gd7jxbK2WY/5qbA8LZGmPEhy/3KcY7veAhwG6UxEiPWxnAmmffPjlON/KEEARIdiBWRJU1YY3KK1OxquAaDlmO2uCShLZ3n2aTb5c=,iv:vFiIGa+2cAVfKVGxofLdhSLTcf6wjsTS7dGic07vmEU=,tag:+pp03M/j50L6r89FubTHSg==,type:str]
    version: 3.13.1
