apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared
  - zot
  - postgres
  - redis
  - temporal
  - traefik-dashboard
  - vaultwarden
  - monitoring
  - flux-receiver
