apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:AkXLNHWd6DFKVLknqljwiG20ylV1J0kOtWs0oDGB1eKLksVuWpRFJg==,iv:ZBYC1taVSsqUc/8SArjLcJ0iHCVmgqkroAKviQocs5k=,tag:imN//OIX2enR9ZEbopaVHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySjRkcVhzdUs5dGVBRkdM
            ZjA4Y1BnOTNzUWlkNHZwV2dXajBLemx3cW1jCkY1dTdUd01zVWxBNlVZZ2Y3NDRk
            a1dZTzlGVytrVEtieDlkUXUwa2RJT3cKLS0tIDdkblBhckRvalViWnlHZE55M2xV
            bFVUZkR4MEpwcFBDSXBhYTYvUXd0R3cKOO2Y2C6+l8tyX2Eq0lOhqX6guYhqhzso
            8yBU028mkyaBT+qRZm5dKCycX1MtkmsGEtvJR0WOC7/KqJY3Iswltw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hysm8fxc6qcgzv96vwdag8hf5rl2j5k6s2jl5asm648enhpgrp0qkxktw7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T03:55:29Z"
    mac: ENC[AES256_GCM,data:/nq5pJNaku0aURvaivVbUqf5j+XDXIBOZUd+CmjpLjKImpIUVBPE+z/zT/i3u24wEjU6W4QX6h9sJUvY5K9IhdcEDM3+HIqpi1kcAp9KHYzq6rmV5kgTnk0Q0IVfYW5O7+HE6t9vuWad153lHLVykskDp10+CgYHk+hORB8RHfg=,iv:SW+GK50drFfDw4yWO6xptY3IEAadfbcrNMXIUGXgCC4=,tag:oHCI74sA1nzlcLT0b3m4GQ==,type:str]
    version: 3.13.1
